### ISSUE TITLE
Pinecil Hall Sensor

### ISSUE THREAD

**Issue by mikerocklewitz** [Ralim/IronOS#1001]
Hey all,

I ordered some hall sensors off of d-key to add the magnetic shutoff to my pinecils.  I followed the schematic from the pine64 wiki and ordered the exact Si7210-B-00-IV(R) as listed.  The installation was pretty straightforward - 5 points to solder.

But....

How do i make it work? It makes no difference what sensitivity I set it to, it does not detect magnetics.

![20210622_074425](https://user-images.githubusercontent.com/63117362/122926746-ce1e1880-d32d-11eb-9f96-d8200afbfdb1.jpg)

**Comment by Ralim** [comment]
Hi,

If the menu setting is showing the sensor is being detected.

Make sure your magnets are _strong_.
I use a large neodymium one mounted near the iron when in the stand.

**Comment by mikerocklewitz** [comment]
The only setting for the hall sensor that I see is sensitivity under sleep settings.

I assume that's the only setting.

**Comment by mikerocklewitz** [comment]
Hah.

it works fine.  Apparently knowing where the magnets are located in the soldering stand is pretty important.

**Comment by discip** [comment]
@mikerocklewitz
Good evening Sir,
is there any chance of you providing information, preferably pictures, of where to install the sensor?

thanks in advance
kind regards

**Comment by mikerocklewitz** [comment]
I apologize for never seeing this. I have a disassemble dead but should be modded board at home. Will get pictures tonight.

**Comment by discip** [comment]
@Ralim
One more question though, which of the SOT23-5 do you recommend?
There is a bunch of 'em listed here https://files.pine64.org/doc/datasheet/pinecil/si7210-datasheet.pdf. 😅

**Comment by Ralim** [comment]
You must match the one in the schematic `Si7210-B-00-IV(R)`

**Comment by discip** [comment]
Thanks!

**Comment by mikerocklewitz** [comment]
> I apologize for not seeing this. I have a disassemble dead but should be modded board at home. Will get pictures tonight.
> 
> Actually ill snap pics when i go on break on 3hrs. I wont keep yall waiting lol

Was that 3 hours? Im not gonna circle it, you can play where's wally or find the bodge work![20220118_182037.jpg](https://user-images.githubusercontent.com/63117362/150043958-916d596e-b953-4deb-adf1-479ac399e5a0.jpg)

**Comment by Ralim** [comment]
Ah you have the newer PCB revision.
Either way, it should be the only unpopulated spot the right size / shape :)

**Comment by discip** [comment]
@mikerocklewitz
> Was that 3 hours? Im not gonna circle it, you can play where's wally or find the bodge work![20220118_182037.jpg]
> ![20220118_182015.jpg](https://user-images.githubusercontent.com/63117362/150044319-d581bc2b-1de4-460b-a27d-466eeb7c9c88.jpg)

Sorry it is me one more time, but it seems that you've photographed 2 times the wrong side of the board 😅,  since the hall sensor belongs on the other side.
That photo made me think the sensor was preinstalled on my device. 🤣

Nevertheless thanks for trying!

Here is a photo @ritkit made showing the spot where the sensor belongs: ![150989371-474e3cb2-295d-4591-a1e7-23af02b2dfc5](https://user-images.githubusercontent.com/53649486/151031538-935e28f6-4d39-4aa6-a013-7283380e16ab.jpg)

**Comment by mikerocklewitz** [comment]
> @mikerocklewitz
> > Was that 3 hours? Im not gonna circle it, you can play where's wally or find the bodge work![20220118_182037.jpg]
> > ![20220118_182015.jpg](https://user-images.githubusercontent.com/63117362/150044319-d581bc2b-1de4-460b-a27d-466eeb7c9c88.jpg)
> 
> Sorry it is me one more time, but it seems that you've photographed 2 times the wrong side of the board 😅,  since the hall sensor belongs on the other side.
> That photo made me think the sensor was preinstalled on my device. 🤣
> 
> Nevertheless thanks for trying!
> 
> Here is a photo @ritkit made showing the spot where the sensor belongs: ![150989371-474e3cb2-295d-4591-a1e7-23af02b2dfc5](https://user-images.githubusercontent.com/53649486/151031538-935e28f6-4d39-4aa6-a013-7283380e16ab.jpg)
> 
> 

Maybe you should look closer. You can clearly see my hall sensor.

Perhaps your board is a different revision?

**Comment by mikerocklewitz** [comment]
> > @mikerocklewitz
> > > Was that 3 hours? Im not gonna circle it, you can play where's wally or find the bodge work![20220118_182037.jpg]
> > > ![20220118_182015.jpg](https://user-images.githubusercontent.com/63117362/150044319-d581bc2b-1de4-460b-a27d-466eeb7c9c88.jpg)
> > 
> > Sorry it is me one more time, but it seems that you've photographed 2 times the wrong side of the board 😅,  since the hall sensor belongs on the other side.
> > That photo made me think the sensor was preinstalled on my device. 🤣
> > 
> > Nevertheless thanks for trying!
> > 
> > Here is a photo @ritkit made showing the spot where the sensor belongs: ![150989371-474e3cb2-295d-4591-a1e7-23af02b2dfc5](https://user-images.githubusercontent.com/53649486/151031538-935e28f6-4d39-4aa6-a013-7283380e16ab.jpg)
> > 
> > 
> 
> Maybe you should look closer. You can clearly see my hall sensor.
> 
> Perhaps your board is a different revision?

Im going to apologize 🤣🤣

I was looking at a chip i removed 
![20220125_120356.jpg](https://user-images.githubusercontent.com/63117362/151033553-27a5888e-7f19-4222-bbe6-2ffd4e7a909a.jpg)

**Comment by discip** [comment]
Ah that's a lot better!
## No need to apologize, every thing is fine be me! 😃👍
Just wanted to make this clear in case someone would see these photos thinking they are showing the populated hall sensor

**Comment by mikerocklewitz** [comment]
If admin can clean this up please do

**Comment by discip** [comment]
@mikerocklewitz
If you want, you could clean it up yourself by choosing **_edit_** after you click the _**3 dots**_ in the _**upper right corner**_ of the corresponding post. Than just swap the wrong photo with the one you posted last.😊

**Comment by mikerocklewitz** [comment]
> @mikerocklewitz
> If you want, you could clean it up yourself by choosing **_edit_** after you click the _**3 dots**_ in the _**upper right corner**_ of the corresponding post. Then just swap the wrong photo with the one you posted last.😊

Yea. It may be a day or two til i get around to it though. I do not like github on my phone.

**Comment by gregknight** [comment]
I guess I should’ve looked at the installation instructions before ordering the sensor, any tips on how to solder something to my soldering iron? 😂

**Comment by mikerocklewitz** [comment]
> I guess I should’ve looked at the installation instructions before ordering the sensor, any tips on how to solder something to my soldering iron? 😂

2 Pinecils are better than one 💁‍♂️
