### ISSUE TITLE
Add the Romanian language

### ISSUE THREAD

**Issue by cipyyy** [Ralim/IronOS#1026]
[translation_RO.zip](https://github.com/Ralim/IronOS/files/6964208/translation_RO.zip)
Hello,
I have attached the file translated into Romanian.
I don't know how to compile to get firmware.
Please help me, I promise to update the file for the Romanian language whenever needed.

**Comment by discip** [comment]
@cipyyy
This can be closed now.
Hopefully. 😅

regards
