### ISSUE TITLE
can't upgrade ts100

### ISSUE THREAD

**Issue by ludov1c** [Ralim/IronOS#1029]
hello i can't upgrade my new ts100 ,
enter in DPU mode : 3.45 , but when i drag and drop the .hex 
![2021-08-20 10_25_10-New Issue · Ralim_IronOS](https://user-images.githubusercontent.com/79090979/130189553-f69d64cc-995c-472e-8d7e-212477b34b06.png)
the file .hex is too long and the ts100 disconnect

**Comment by Ralim** [comment]
Hello,

Can you confirm that at the time of trying this, the screen is showing "DFU"?
Can you confirm you have extracted the file before attempting to copy it to the drive?
Can you confirm you have no anti-virus that supports file scanning on access turned on?
Can you confirm you have tried the double drag and drop method as mentioned [here](https://github.com/Ralim/IronOS/blob/master/Documentation/Flashing.md#miniware-the-file-is-showing-up-with-the-extension-err)?

**Comment by pellz0r** [comment]
I've had this issue as well. Plugging it in another USB port solved it for me.

**Comment by ludov1c** [comment]
i can upgrade only with the MINI218.HEX official, i will try  with no anti-virus

**Comment by Ralim** [comment]
Please also try with the English IronOS firmware release as its the most tested.

**Comment by discip** [comment]
@ludov1c
Good evening Sir,
is this solved?
If so, please close this issue.

thanks in advance
