### ISSUE TITLE
debug menu printing DC, QC or PD instead of 0, 1, 2

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS#1062]
@Ralim
Sorry to bother you again,
but since you changed **`PCB`** to **`ACC`**.
I Think for consistency it would be great, if **`PWR`** would also not be encrypted printing a number, but **`DC`**, **`QC`** or **`PD`** instead.

I looked into **`GUIThread.cpp`** but realized, there are other things going on than with formerly **`PCB`**.
So, may I humbly ask, if you would do this as well? 🥺

**Comment by Ralim** [comment]
Ah yeah fair call
Probably late tonight / tomorrow :)

**Comment by discip** [comment]
Looking forward to this, and definitively willing to test! 😁

**Comment by Ralim** [comment]
There you go :)
Looks to work for me but will wait for your test as I dont have a QC source handy

**Comment by discip** [comment]
@Ralim
Thank you! 👍
Works for me as well!
