### ISSUE TITLE
Updated translation_IT.json

### ISSUE THREAD

**Issue by x86Gr** [Ralim/IronOS#1066]
Hello, I've attached an updated IT translation. First time in github, be patient.

[translation_IT.zip](https://github.com/Ralim/IronOS/files/7229385/translation_IT.zip)

**Comment by discip** [comment]
On that topic, you have to talk to @federicodilo, because he maintains the already existing **`translation_IT.json`** https://github.com/Ralim/IronOS/issues/948#issuecomment-830804088.

**Comment by Ralim** [comment]
Thank you both :)
Closing this as #1069 includes all of this afaik.
If not please reopen :)
