### ISSUE TITLE
Please, add descriptions for translators

### ISSUE THREAD

**Issue by playday3008** [Ralim/IronOS#1092]
Like describe expected behavior after change some setting, etc.

**Comment by Devnol** [comment]
I second this, also provide some context as some languages have multiple translations for one word

**Comment by Ralim** [comment]
How do you want this to be conveyed?
We could expand out the html editor and add descriptions in the defs file?

**Comment by Devnol** [comment]
I don't have any particular way in mind but ideally yeah either a description of what exactly is the context of the string we're translating, where it can be found in the menus and stuff by adding a description field the same way there's a length field I guess.

**Comment by Ralim** [comment]
@playday3008  and @Devnol 
I've added descriptions to the defs file in #1183, if you feel like giving them  a pass to see if they are helpful / what I've missed.

Also creating a script to auto-gen some docs for the repo on a settings break down that is open to criticisms.

**Comment by Ralim** [comment]
Going to consider this covered now we have helptext in the editor (and it will also show up in the docs folder)
