### ISSUE TITLE
Docs: Wiki: Grammar: Space before parentheses

### ISSUE THREAD

**Issue by Jonta** [Ralim/IronOS#1101]
https://github.com/Ralim/IronOS/wiki

### Old

The original software for the iron worked really well, except that if you wanted to change most of the settings you had to connect it to a computer via USB and edit a text document.(This has been changed in the new 2.17 firmware)

Most of the code for the system has been completely re-written for this implementation, attempting to move to hardware peripherals for all the IO rather than software driven events(as the minidso firmware does).

### New

The original software for the iron worked really well, except that if you wanted to change most of the settings you had to connect it to a computer via USB and edit a text document. (This has been changed in the new 2.17 firmware)

Most of the code for the system has been completely re-written for this implementation, attempting to move to hardware peripherals for all the IO rather than software driven events (as the minidso firmware does).

**Comment by Ralim** [comment]
Thanks.
The wiki is fairly unloved at this point sadly :(
