### ISSUE TITLE
Pinecil Stuck on Startup and auto rotation not working RC2.16

### ISSUE THREAD

**Issue by karl03** [Ralim/IronOS#1102]
After updating my pinecil to 2.16 via any method, it is stuck on this screen of random pixels for roughly 30 seconds. It then boots up normally, but the accelerometer is not working. If I reset settings, the behaviour continues, but instead of random pixels it now shows the menu page for power limit with "off" next to it for the same amount of time. This seems to sometimes change to some other menu item, it has now changed to the temperature unit menu.

![20211009_165258](https://user-images.githubusercontent.com/41700374/136665605-84135551-6cf5-47bc-943d-2172b3f404be.jpg)

![20211009_165346](https://user-images.githubusercontent.com/41700374/136665611-ff15be0e-a7a5-42b0-8210-da973920293c.jpg)

Pressing any buttons at this point does not do anything.

If there was a custom logo installed previously it will be stuck on that for 30 seconds instead of random pixels.

**To Reproduce**
1. Flash iron with 2.16RC
2. Power up iron

**Expected behavior**
For the iron to function normally.

**Details on your device:**
 
 - Device: Pinecil
 - Debug menu says PCB 5
 - Release: 2.16.E0CCC69
 - Power adapter being used: Powered off pc
 - If this is an acceleromter related issue, please include its model number here: Says "None" on 2.16 not sure how to check on 2.15 but auto rotate does work on 2.15

**Comment by karl03** [comment]
Thank you very much, this has fixed all the issues.
One weird quirk I have noticed is that it will heat up off any power. So for example I can make it heat up off my laptop usb port (It runs at 2w and heats up very slowly) but just thought I'd mention this.

**Comment by discip** [comment]
@karl03
Good evening,
please close the issue, since your initial problem is solved.
thanks
regards
