### ISSUE TITLE
Pinecil Max Temperature Lower than it should be

### ISSUE THREAD

**Issue by Gringl** [Ralim/IronOS#1105]
**Describe the bug**

The max temperature is capped at 579F (303C) and It won't let me set it higher than this, even though the Pinecil can go up to 752F (400C).
When I hold down or tap the + button to increase the temperature it won't let me increase the temperature past 579F

**To Reproduce**

For the Iron to be able to go to 752F (400C) 

**Details on your device:**
 
 - Device: [Pinecil]
 - Release: [2.16.D6AF465]
 - Power adapter being used: Apple 96 W charger

**Additional context**

I tried with another USBc adapter and it still could not set the temperature higher.

**Comment by Ralim** [comment]
Please test with the files attached to this run once it finishes : https://github.com/Ralim/IronOS/actions/runs/1350275748

**Comment by Gringl** [comment]
That fixed it, thank you :)
