### ISSUE TITLE
What about Miniware DT71 tweezers

### ISSUE THREAD

**Issue by Terratm** [Ralim/IronOS#1122]
Hello, what about Miniware DT7 tweezers support? I would like to see in it extended language support and other extensions that can be added.

**Comment by Ralim** [comment]
Two reasons that I haven't touched the tweezers:

(1) the hardware is wildly different in terms of what it does and how it work, so it would have to be an entirely new firmware that can just use some of the tooling from this repo

(2) the tweezers are NOT open source, neither schematics or source code are open. And I don't have time to tear them down and reverse engineer them.
