### ISSUE TITLE
Des 68 Soldering Iron

### ISSUE THREAD

**Issue by VerseLLC** [Ralim/IronOS#1142]
I just found the Des 68 while browsing aliexpress. It has usb c pd/qc and seems quite nice for the price. I have can't seem to find any info on the chip used. It doesn't have an oled screen like the others though, seems to be a bit more basic with 7 segment digits. I could be wrong, but it seems like a fairly new product.

Here is one of the listings I found https://www.aliexpress.com/item/1005003269049376.html?

Does anyone know anything about this soldering iron or if it could be supported?

**Comment by Ralim** [comment]
If they release schematics happy to look at how hard support would be. 

Would be a bit messy with the different sleep type.

For that price though I would just buy 5 pinecils or a TS80P+TS100
