### ISSUE TITLE
_clear_logo.hex not working (Win10)

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS#1173]
**Describe the bug**
Not able to flash *_clear_logo.hex*

resulting in ***.ERR***

**Details of your device:**
device|firmware
-|-
**TS80P**|build https://github.com/Ralim/IronOS/commit/5058e18138635b87978e24db58bf4c58c60e0a15
PC|Win10

**Additional context**
Tried flashing it several times.
Flashing the firmware.hex works as intended though!

**Comment by Ralim** [comment]
You have not downloaded the python code correctly, from that error I suspect you have saved the github webpage preview not the file itself. Need to hit the `raw` button to get to this page https://raw.githubusercontent.com/Ralim/IronOS/master/Bootup%20Logo/python_logo_converter/img2ts100.py

Then save and run that code

**Comment by discip** [comment]
Ok! I see!🤦‍♂️
Will give that a shot and report back.

**Comment by discip** [comment]
That indeed worked, but I am not able to remove the logo again using *_clear_logo.hex*.

**Comment by Ralim** [comment]
Did you do the double copy trick for the hex file?

**Comment by discip** [comment]
Yes! I did.

**Comment by Ralim** [comment]
>ps: I thought the custom logo would replace the quick flashing miniware logo, but that did not happen.
Is that not replaceable?

That is part of their bootloader, so cant remove it without removing their bootloader.

**Comment by discip** [comment]
> That is part of their bootloader, so cant remove it without removing their bootloader.

Ok. I see. So someone should rewrite the bootloader to solve this right? 😁

**Comment by Ralim** [comment]
So you can flash the DFU bootloader instead, which fixes this, but also removes the usb-drive functionality entirely and you have to use dfu-util to flash instead.

Thats about all you can do to remove their logo for now. I have not undertaken writing a "new" bootloader that does the usb stuff. I have been thinking about writing a usb-dfu one that I maintain for these units. But low priority project for now.

Just dont have enough time to build all the things... :/

**Comment by discip** [comment]
No problem! 👍
I am good with that. If there will be one day a *usb-dfu one*, I will be happy, but until than I will just stick to the current situation. 😊

Could it be that *_clear_logo.hex* does not work due to my iron using **DFU3.50** instead **DFU3.45**?

**Comment by discip** [comment]
> So you can flash the DFU bootloader instead, which fixes this, but also removes the usb-drive functionality entirely and you have to use dfu-util to flash instead.

Is there a way to go back to the *miniware* bootloader after that?

**Comment by discip** [comment]
Am I the only one to not get this to work?
# Could someone please check, if `_clear_logo.hex` is working?

thanks in advance

**Comment by discip** [comment]
Anyone?

**Comment by Ralim** [comment]
Planning to test next time I boot windows..it's been a bit

**Comment by L1cardo** [comment]
Same here, I can not remove the custom boot logo either

**Comment by L1cardo** [comment]
> If you are on Pinecil or a dfu bootloader you can just erase the flash easily.
> Otherwise could you give this a test:
> [erase_test.zip](https://github.com/Ralim/IronOS/files/8060244/erase_test.zip)

I am using TS80P, and this one works!
