### ISSUE TITLE
Display error, soldering iron did not check.

### ISSUE THREAD

**Issue by Eugene-Market** [Ralim/IronOS#1194]
**Describe the bug**

To Reproduce
1. I download the firmware with the button pressed.
2. I'm waiting until the soldering iron folder is reopened.
3. I turn on the power.

Expected behavior
The outlines of the logo appear, but mixed with noise, and all this is constantly moving.

**Details of your device:**

 - Device: ts100
 - Release: 2.20
 - Power adapter being used: USB, 24 volt power supply

**Additional context**
#148 and #149 worked best, but the soldering iron did not work, on the official firmware everything works fine :)

**Comment by Ralim** [comment]
This is a duplicate issue  please see other issues about the ts100 new model that is being shipped with an unsupported microcontroller.
