### ISSUE TITLE
Feature enhancements

### ISSUE THREAD

**Issue by PUF52** [Ralim/IronOS#1195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PUF52** [comment]
--I ask you what in this situation what should I do .. Throw out the non-working TS100 or try to restore it. I ask for help with determining the probable causes of "Sen ERR".
Юрий

**Comment by CRImier** [comment]
This is how your first message shows up:

![image](https://user-images.githubusercontent.com/3173633/150641148-e34fe90d-ce11-4379-a43b-fa97b190e6c0.png)

You might have missed some text there?

**Comment by Ralim** [comment]
as an admin I checked and the request has no content hidden even in comments either.
As such I'm going to close this. Feel free to open this up after you have edited the issue to show what you wanted help with.

Noting from your email its about `Sen ERR` which is NOT part of this firmware. Ror Sen ERR help you will need to talk to Miniware on their forums.
