### ISSUE TITLE
Update VBus mod check location

### ISSUE THREAD

**Issue by Ralim** [Ralim/IronOS#1226]
Need to move VBus mod probing out of debug menu or cache results to prevent timeouts with PPS.

This is basically cosmetic, it does not affect normal operation. Just that PPS times out while you view this in the debug menu if you are currently using a PPS contract. 

Only issue is that the timeout means the power source will power cycle the device while you have this menu open.

**Comment by River-b** [comment]
Where will the Vbus Mod probing be located now? I don't see it in the menu or is it not possible to have it due to PPS issues? thanks

**Comment by Ralim** [comment]
It will still show up on the debug menu when you use a pd charger. Just that I need to move the code that does this
