### ISSUE TITLE
[Pinecil] Iron reports temperature of 503C and won't heat

### ISSUE THREAD

**Issue by rbrian** [Ralim/IronOS#1234]
**Describe the bug**
After updating to 2.17, my Pinecil displays a temperature of 503, and of course won't heat. 

**To Reproduce**

 - Device: [e.g. TS80/Pinecil etc] Pinecil
 - Release: [eg 2.15.40087E6] v2.17.E065BE3
 - Power adapter being used: Laptop power brick
 - If this is an accelerometer related issue, please include its model number here:

**Additional context**

**Comment by River-b** [comment]
when you go back to 2.16 or 21.5  does the problem go away?  can you repeat it every time you load 2.17 again?
what are the exact specs on the  Power adaptor back just for reference.

**Comment by River-b** [comment]
also I'm personally in the discord now, but if you could join the live discord chat in Pinecil or whatever other Pine64 forum chat you use.  there will be people here that can help you step through the diagnosis.

**Comment by Ralim** [comment]
@rbrian 

So first step would be to roll back down to what you were on before and check that the issue goes away.
if it does go away, if you could then list out the reading in `rtip` and `chan` in the debug menu it would be fantastic.

Where did you purchase your Pinecil from?

**Comment by River-b** [comment]
To get to the  reading for  Rtip and Chan, you need to enter the DEbug menu,  
Long hold down (-)  rear button, then use  (+) to scroll through settings

**Comment by rbrian** [comment]
(posted on Discord) 2.15 works, 2.16 doesn't. in 2.16, rtip fluctuates around 1000, chan is 65036. pinecil was purchased from amazon. in 2.15, rtip is ~750, chan is 470

**Comment by rbrian** [comment]
![Uploading F671BCAA-B8B6-4F5E-B6DB-B3B14174CB46.jpeg…]()

**Comment by rbrian** [comment]
![15B6BB4C-4D64-4591-86F8-9591A7AFDD20](https://user-images.githubusercontent.com/151535/154330476-f75690dd-8f33-4dbe-93ff-e5cbc52c4608.jpeg)

**Comment by Noshbit** [comment]
Similar issue with different readings (also already in contact with pine dev team on telegram)
RTip reads around 800 when idle and CHan is 1320 when idle. On stock firmware, 2.15 and 2.17

**Comment by River-b** [comment]
> 

only 2.15 works for you?
  but 2.16 and 2.17  have same issue, both  very high Chan readings,  shows high temp  500 but no heat?

**Comment by rbrian** [comment]
2.14.1 worked as well. Not sure what I was using before yesterday... Whatever was current mid November.

**Comment by Ralim** [comment]
A CHan of `65036` is extremely suspect to a problem with the cold junction compensation temperature sensor.
It is probably worth inspecting the solder joints on the TMP36 device to make sure it doesnt have a weak solder joint.

newer firmware runs the ADC a bit faster to keep tighter control of the tip temperature. Normally this wont cause an issue as the output from the TMP36 is powerful enough to keep up without any issue. But if you have a weak or cold solder joint this could cause issues.

**Comment by rbrian** [comment]
Reflowed U10 (by hand) . Works now with 2.17. Had to add solder (used lead-free SAC305 solder paste because my wire solder is leaded, and i assume since the case says RoHS that it's unleaded). 

Schematic:  ![image](https://user-images.githubusercontent.com/151535/154550331-9d3bc201-7e01-4ae8-a4ed-2cf46ac185ff.png)

Before: ![Quick Camera Image 2022-02-16 at 3 35 24 PM](https://user-images.githubusercontent.com/151535/154550601-ecc23739-c4d5-4620-9bde-ef716eefee33.png)
 
After: ![Quick Camera Image 2022-02-17 at 10 56 29 AM](https://user-images.githubusercontent.com/151535/154551466-7b0b36fb-19b8-4398-995e-4885887b94e8.png)

**Comment by River-b** [comment]
> 

fyi, it's ok to use leaded for repair. The Manufacturer has to use no-lead.

**Comment by rbrian** [comment]
I've read that mixing lead and no-lead can lead to circuit failure, so I try to be careful.

**Comment by Johnex** [comment]
You can use some solder wick to remove the leadfree, then use some flux, and lastly use the leaded solder :)

**Comment by River-b** [comment]
> ome solder wick to remove the leadfree, then use some flux, and lastly use the leaded solder :)

that is what I did on mine, wicked off what I could then solder on new stuff
