### ISSUE TITLE
Custom logo is not shown on TS80P 2.17.E065BE3

### ISSUE THREAD

**Issue by the-remmer** [Ralim/IronOS#1267]
**Describe the bug**

I followed the documentation to use a custom splashscreen, but the default miniware logo is still being shown.

I hope this is not a user error but I tried so many times, I think I'm doing exactly what the documentation is saying.

**To Reproduce**

1. Download and decompress [https://github.com/Ralim/IronOS-Meta/releases/download/v2022.02.15/miniware.zip](https://github.com/Ralim/IronOS-Meta/releases/download/v2022.02.15/miniware.zip)
2. Connect the TS80P to Windows in DFU mode
3. Drag and drop `IronOS.png.hex`
4. The Iron disconnects and reconnects, the file becomes `IRONOS~1.RDY`
5. Disconnect the Iron
6. Plug the iron in the power brick, the Miniware logo is still displayed

**Expected behavior**

The custom logo should be displayed instead.

**Details of your device:**
 
 - Device: TS80P
 - Release: 2.17.E065BE3 
 - Power adapter being used: The one provided by NovelLife (Travel Charger Model QC09, PD+QC3.0 45W)

**Additional context**

- I tried also with an animated logo and my custom logo that I converted with the command `python3 .\img2logo.py -P preview.png -m .\mylogo.png out`. The preview works and looks good, the `.dfu` and `.hex` files are generated, the `.hex` files gets replaced with `.RDY`, but still no change.
- I installed IronOS the exact same way by connecting the iron in DFU mode and drag & dropping the `.hex` file, and it worked perfectly fine.
- I tried to drag & drop the `.dfu` file but the copy fails (which was expected I guess). With the `.hex` file the copy works and it is replaced with the `.RDY` file.
- I also tried renaming the file just `a.hex` so it wouldn't be truncated with the shortname `~1`.
- I tried a factory reset.

**Comment by the-remmer** [comment]
Ok I tried to update the firmware to bleeding edge ([https://github.com/Ralim/IronOS/actions/runs/1991864575#artifacts](https://github.com/Ralim/IronOS/actions/runs/1991864575#artifacts)) and it works now. I guess it is being fixed.

**Comment by discip** [comment]
This seems to be fixed. Right?
Than please consider closing this issue. 😊

thanks
kind regards

**Comment by Ralim** [comment]
Ah rightio, so 2.17 uses the older format, while the current main branch uses the ironos-meta generated logo's.

You have hit right in the middle of the transition period

**Comment by SimonTechv** [comment]
Does not work also with ts100.
