### ISSUE TITLE
cc1: error: ./Core/Drivers/usb-pd/include: No such file or directory [-Werror=missing-include-dirs]

### ISSUE THREAD

**Issue by Bushmills** [Ralim/IronOS#1271]
After fresh clone, make would fail with that error:
cc1: error: ./Core/Drivers/usb-pd/include: No such file or directory [-Werror=missing-include-dirs]
 
After manually creating that directory, compiling went on (but stopped at an error related to missing bdflib, I guess I'll have to read about prerequisites first)

**Comment by Ralim** [comment]
Duplicate of: https://github.com/Ralim/IronOS/discussions/1268

You have not recursively cloned the repository

**Comment by Bushmills** [comment]
Thank you. Apparently it helps sometimes to read the docs.
