### ISSUE TITLE
not working infinite logo on the ts100.

### ISSUE THREAD

**Issue by 3eGo** [Ralim/IronOS#1285]
i have a problem with the firmware of the ts100.
in the latest version you have added the time of the bootup logo which can also be infinite.
when i set that setting i get no result of the logo staying on screen all the time or at least until i press a button.
am I doing something wrong or is it not working correctly? thank you very much in advance of the reply

**Comment by federicodilo** [comment]
In order to get your options effective you need first to exit to the main screen.
It should work for you too.

**Comment by 3eGo** [comment]
yes but I've always done it that way.
then when I return to the settings it shows me that it is selected on the infinite logo mode.
the problem is that the setting just doesn't work unlike the others.

**Comment by federicodilo** [comment]
I find this quite strange since it works as intended on my TS100.
Are you using a custom animation? Have you tried other animations/static images?
Can you please provide a video of the problem?

**Comment by 3eGo** [comment]
no i am not using a custom animation and i also tried to change other static imagesit but nothing, it just keeps not going.
now I try to make a video with all.

**Comment by 3eGo** [comment]
https://user-images.githubusercontent.com/104205730/164997023-dc4ba6c2-4500-437a-ad19-033e51e554c3.mp4

**Comment by discip** [comment]
@3eGo 
Maybe you could try reflashing the firmware.

**Comment by federicodilo** [comment]
Curiously enough it lasts 5 s, I suspect it depends on how the timers are internally managed.
Maybe @Ralim has some ideas about it. Can you please take a photo of the inside?

**Comment by 3eGo** [comment]
what i have to do?

**Comment by 3eGo** [comment]
I also tried to put other firmware, change versions and more, but nothing has ever changed

**Comment by Ralim** [comment]
Can you please try the firmware from https://github.com/Ralim/IronOS/actions/runs/2460121981 when you have time 😁

**Comment by discip** [comment]
@3eGo
Please respond to the developer’s request.

And could you also please test this version  https://github.com/discip/IronOS/suites/6892990972/artifacts/267234503?

thanks in advance

**Comment by discip** [comment]
@3eGo
Are you still interested in this issue getting solved? 🤷🏻‍♂️
Please test the latest firmware, prior to responding.

**Comment by discip** [comment]
@3eGo
Please try the latest firmware to make sure your issue is solved.
And please do not forget to close this. 😊

**Comment by 3eGo** [comment]
oh sorry, I hadn't seen the emails arrive, now i check

**Comment by 3eGo** [comment]
yes it works
