### ISSUE TITLE
Horizontal offset of display TS100

### ISSUE THREAD

**Issue by lanefloch** [Ralim/IronOS#1292]
Just got a new TS100 off amazon and flashed it. But it seems the screen has a large offset horizontally. Not sure if there is a setting to compensate for this. Thanks for your help!
![IMG_4844](https://user-images.githubusercontent.com/20210356/166374561-ee8b9535-9ce9-403c-bb54-9f2d6e2edd19.jpg)
![IMG_4845](https://user-images.githubusercontent.com/20210356/166374674-874a7e9c-e663-46e9-a014-2cdaeb00b623.jpg)

**Comment by Ralim** [comment]
There is not a setting as of present.
That would almost look like the screen is not the correct model (as its expecting a different horizontal offset).
If you flash the miniware firmware does it work?
What DFU version is your TS100?
Is it actually a TS100 or a clone?

**Comment by discip** [comment]
Try to use a magnifying glass to inspect, if the oled is physically shifted inside the device.

**Comment by lanefloch** [comment]
Ok upon further inspection the entire OLED is physically shifted within the Iron. Thanks for the help!
