### ISSUE TITLE
Not able to Flash TS100

### ISSUE THREAD

**Issue by TimoHie** [Ralim/IronOS#1305]
**Describe the bug**
My issue is that whenever I try to flash the firmware Windows tells me that the devise I try to flash does not exist

**To Reproduce**
![TS100](https://user-images.githubusercontent.com/83012948/172044881-7c04d697-feeb-4f90-8730-45d19d3cbb6f.PNG)
 I plug in the Soldering Iron while holding the according button to enter DFU mode, in my case it's DFU 3.48. A folder opens with two hidden folders inside (.fseventsd and .Trashes) and another TRASHES file as soon as I try to move the .hex in I get this error (screenshot above), after that the folder disappears and I get the error ''F:\ is unavailable''. Also the soldering iron is not turning on anymore now, only per usb in DFU

**Comment by Ralim** [comment]
Please search other existing issues.
This is not an issue with this firmware.
This is an issue with the Miniware bootloader.

Please see:
#1295 
#1276 
#1214 
#1213
#1199 
#1198
#1177
#1170
#1155
