### ISSUE TITLE
start temp 208°C @ 25 room temp

### ISSUE THREAD

**Issue by H2o-r3D** [Ralim/IronOS#1315]
**Describe the bug**
Indicated temperature of the tip without heating up 208°C @ 25 room temp

**Details of your device:**

* DFU: 3,45
* purchased circa 2019

 - Device:
 -  TS100
 - HW G 206
 - HW M 189
 - HW P 228
 - RTip 729
 - CTip 210
 - CHan 2100
 - Vin 24,5
 - Release 2.18.70565DE
 - Power adapter being used: DC24V PSU

**Additional context**
With the normal firmware(FW) the temperature detection works normally.

Update with your FW 2,18:
Hold key A, plug in USB, copy TS-100_en to 7ABB9D94 folder, reboot, .rdy file

Flir thermal image says in hotspot circa 150°C
target temperature: 330°C
real room temperature: 25°C
TS100 displayed peak temperature:208°C (without heating up)

Tested and same error pattern:
* Calibration
* 2 different tips
* FW 2.18 (de & eng) & 2.04 (de)

**Comment by H2o-r3D** [comment]
![Ts100](https://user-images.githubusercontent.com/107677336/174274747-5c8601ce-fbdf-4a20-b915-7226d786cf22.jpg)

**Comment by H2o-r3D** [comment]
![TS100](https://user-images.githubusercontent.com/107677336/174275440-4cdabd60-93ea-4fd5-abf6-ba332dd59569.jpg)

**Comment by Ralim** [comment]
Your posted CHan is reporting 210C as the temperature for the PCB. That sounds unlikely.

Can you measure the output voltage on your tmp36?
Can you check the daughter board is correctly mounted ?

**Comment by H2o-r3D** [comment]
![TS100](https://user-images.githubusercontent.com/107677336/174277786-b433e9cc-ca1e-4f34-8652-368fa0fcdd7c.jpg)


Excuse my not knowing, what do you mean by tmp36?

**Comment by Ralim** [comment]
Device U6 near the handle measures the PCB temperature. If it's not soldered correctly or damaged it's signal doesn't make it to the MCU correctly and you see this sort of behaviour. (It's between the copper contacts)

Also check the small board is connected to the main board correctly.a loose or damaged contact there can also do thus

**Comment by H2o-r3D** [comment]
![TS1002](https://user-images.githubusercontent.com/107677336/174283884-84b1ead6-a064-48c3-9a3f-4516afa868fa.jpg)

I have to measure the two contacts or?

**Comment by Ralim** [comment]
Ah yes those are the correct pins to measure. It should be around 0.5-0.6V range if it is operating correctly. 


That would explain why the sensor readings are so high.
I would suggest checking the voltages on the other pins; if they are as expected (shutdown pulled high, vs at 3.3 ish volts) it would suggest the part has been damaged.

**Comment by H2o-r3D** [comment]
I just measured the pins Vs to shutdown. Measured value: 0V 
Do you know the correct designation of the TMP 36? This component size can be easily exchanged. 

I opened the TS100 from my buddy. I noticed that on the small board the smaller chip is on the other side. With me it is on the right side (as you can see on the picture above) and with my friend it is on the left side. Are there still differences or does this not matter?

**Comment by Ralim** [comment]
Hia,

I would suggest a component replacement if you can.

You should be able to match the text on the top of your device to get the right mod; or check the schematic.

Of your reading 0V from supply to shutdown then I see no reason why it wouldn't be working.

The small part you are talking about is the accelerometer. If you check in the debug menu your friend most likely has a different accelerometer model. Miniware just fits whichever model is cheapest at the time.

**Comment by H2o-r3D** [comment]
Thanks for your help. I will try to repair the defect.
