### ISSUE TITLE
TS100: graphics is slightly overlaped

### ISSUE THREAD

**Issue by sorgelig** [Ralim/IronOS#1317]
**Describe the bug**
![20220622_063552](https://user-images.githubusercontent.com/917089/174908323-be146ff8-6311-4f74-8c50-35d79b166109.jpg)

Just updated to v2.18 and noticed graphics overlap at the right edge on symbols C and V.
Version is TS100_EN.

I have also Pinecil soldering iron. It doesn't have such problem.

**Comment by federicodilo** [comment]
Just to confirm that's a model related issue, mine is fine.
![photo_2022-06-24_13-52-49](https://user-images.githubusercontent.com/68966053/175530784-45428c0c-4986-412b-a54a-2b737acab9b1.jpg)
 ![photo_2022-06-24_13-52-51](https://user-images.githubusercontent.com/68966053/175529971-16aaad19-1d48-41a0-9ee4-0da827010b9c.jpg)

**Comment by sorgelig** [comment]
my TS100 is at least 2 years old. How to provide more info about specific model?
I don't know how OLED is addressed, but can it be some race condition of graphic buffer filling and pulling it out over I2C/SPI to OLED?

**Comment by Ralim** [comment]
This is super odd.

Could I ask you to try going back to 2.17 and testing and then coming back forwards to 2.18 and testing? Just want to (1) rule out bad flash and (2) see if it's new.

I'm really not sure what going on here; we pre render the whole screen and then draw it in one transaction. So I would expect it to occur on other devices too.

I'll have to dig out my ts100 and see if I can make it happen for me.

**Comment by sorgelig** [comment]
i've tried already v2.17 - same issue. Went back to v2.18. Tried different languages (Russian, English). It only happens in Detailed view mode. Non-detailed view don't have such issue.

**Comment by sorgelig** [comment]
after more precise inspection it seems screen is broken. In some cases it displays that column, but in other cases doesn't.

**Comment by Ralim** [comment]
Ah I'm sorry to hear it's the screen.

The screens are fairly cheap and not too hard to replace if you decide to try.

**Comment by sorgelig** [comment]
it's very minor break. So i will use it as is till it completely break. Then i will use my spare TS100, haha :)
Also want to switch to Pinecil, and it's good i can re-use whole set of TS100 tips with it.
