### ISSUE TITLE
Pinecil v1.1 includes vbus mod

### ISSUE THREAD

**Issue by GabyPCgeeK** [Ralim/IronOS#1321]
I've looked around and haven't found any reference to this so here it is. 

I bought a Pinecil and IronOS reported "PD No VBus" and upon opening it I found out that it has a v1.1 board. The FBUS302 vbus pin is routed to an unpopulated resistor.

![20220627_141707](https://user-images.githubusercontent.com/28073116/176012317-160d43ee-a6cc-4009-b243-b03f5d799cf3.jpg)

![20220627_141409](https://user-images.githubusercontent.com/28073116/176012332-3d5b34df-409e-4d69-a162-6ebf557d98bd.jpg)

**Comment by River-b** [comment]
hello, could you please post photo of the Back side of this new PCB.  I want to see the production number.  it would be on the side where there is an empty spot to add hall sensor near the U14  spot on the PCB.

**Comment by River-b** [comment]
indeed it looks like the PCB has been updated

**Comment by GabyPCgeeK** [comment]
![20220630_141626](https://user-images.githubusercontent.com/28073116/176754389-68451a2a-6259-43bc-8615-c9655c82a6b9.jpg)


![20220630_141728](https://user-images.githubusercontent.com/28073116/176754405-d6283dca-4e46-4a82-bcdb-5fc8a9fab30f.jpg)


![20220630_141815](https://user-images.githubusercontent.com/28073116/176754421-cbb32f84-69f3-49f5-b67a-4f1eba191bf2.jpg)


![20220630_141830](https://user-images.githubusercontent.com/28073116/176754457-8bb27db0-eb0f-4c5a-a22d-19227a354c0e.jpg)


![20220630_141842](https://user-images.githubusercontent.com/28073116/176754480-90bda7d6-c9d7-47cf-9799-f88f3f06eea9.jpg)

**Comment by River-b** [comment]
2213 ,  this has production date of 13th week of 2022  , so April 2022. 
Indeed it looks like the PCB changed. 
Just to confirm,  did you buy this directly from  Pine64.com  or the official Pine64 store on Amazon USA?

would have to see if we could get confirmation from Pine64 of this PCB change so we won't have to cut the trace anymore to get the DC 24V  modification safely.   For now It is good idea to check with the IronOS firmware first like you did and if it says "PD No Vbus"  - then do not cut the trace. 

Also could you  show photo of the outer Case?  does the case still say 12V-21V  or has it changes to 12V-24V ?

**Comment by GabyPCgeeK** [comment]
Bought it from Amazon on Jun 21.

[20220702_230712.jpg](https://user-images.githubusercontent.com/28073116/177024289-db0876b7-6fb4-4922-88d9-e4b09f67b4e9.jpg)

**Comment by River-b** [comment]
nice high res photos. thanks

**Comment by discip** [comment]
@GabyPCgeeK
Since this is no issue you maybe want to close this and move it to the discussion. 😊

thanks
