### ISSUE TITLE
delete Logo.md  install directions, send everyone to IronOS-Meta for that

### ISSUE THREAD

**Issue by River-Mochi** [Ralim/IronOS#1356]
I would like to completely delete the Logo.md file that is in this IronOS here:

https://github.com/Ralim/IronOS/blob/dev/Documentation/Logo.md

and just put a link here in https://github.com/Ralim/IronOS/tree/dev/Bootup%20Logo
It would sends everyone over to IronOS-Meta  since they have to go there anyway to get the Images and Python scripts.

This way the Instructions for making Boot Logo images and storage of them is only updated/maintained in one place, in the IronOS-Meta. and linked to from IronOS firmware.

![image](https://user-images.githubusercontent.com/97197236/183005688-37e02d84-8f1c-49ad-8bd0-1a4b8c3d439e.png)

I already put the Logo.md imformation completely in the README.md over in IronOS-Meta and did PR for it. Would be nice to just maintain Install instructions for Logos in one place.

**Comment by River-b** [comment]
Also Joric recommended "I'd recommend removing custom sidebar from wiki. Stock sidebar supports anchors/sections automatically and looks generally better now.

**Comment by discip** [comment]
@Ralim
Most likely you missed that. 😄
Should this be done like that?

**Comment by River-b** [comment]
This is so old I need to review this to see if it's even relevant now.  I haven't looked at the instructions in a while and this is from 6 months ago.
