### ISSUE TITLE
Add configuration file with default settings

### ISSUE THREAD

**Issue by nikkyxxx** [Ralim/IronOS#1411]
After switch on or after week up lock key mode was reset to defaults include lock key mode is off.
I want put configuration file to TS100 with default settings for lock key mode is on by default. 
After week up or switch on lock key mode should be restore to be on.

**Comment by discip** [comment]
@nikkyxxx
Is your issue still present?
Please do not forget to close this, if not. 😀

**Comment by discip** [comment]
@nikkyxxx
Sorry, but I am not able to follow.
Could you please try to rephrase your request?

**Comment by discip** [comment]
Closing due to lack of response.
