### ISSUE TITLE
V2 Pinecil reboots when attempting to heat tip on DC barrel jack input with 6.2ohm tip (PD is ok and so are 8ohm tips)

### ISSUE THREAD

**Issue by howels** [Ralim/IronOS#1426]
**Describe the bug**
V2 Pinecil connects to DC supplies that work with the TS100. However when pressing "+" to begin heating the iron restarts and comes back without initiating the heating process. Tested both 12V and 24V supplies both of which work well with the TS100.
Iron works on PD input, happily drawing 60W without problems.
When connecting to a 3S lipo the iron work ok too - suggesting that the iron is experiencing voltage sag from these DC supplies (rated at 24V/5A and supplies 60W to my TS100 so should be ok).

**To Reproduce**
Connect Pinecil V2 to DC barrel jack power input. Initiate heating.

**Expected behavior**
Pinecil v2 should be tolerant of voltage fluctuations from DC supplies as these are rarely perfect.

**Details of your device:**
Pinecil v2, bought direct from pine store, arrived today.
24V/5A and 12V/3A supplies tested (not working) along with 65W PD USB power (working) and 3S li-ion (working).

**Comment by howels** [comment]
It appears that the new lower resistance 6.2 ohm tip is to blame. Swapping for the prior TS-I 8ohm tips allows the iron to behave fine. However this supply is 24V/5A and should be able to push 120W so I suspect that the DC power input circuitry is to blame?

**Comment by howels** [comment]
> This looks most likely like your 24V and 12V supplies (or cabling used) are not actually up to the job. OR it could be that they are "smart" power supplies with short circuit protection that is tripping. Voltage drop inside the iron is very,very small and would not cause this.

Any way to determine the exact cause? I test brushless motors for quadcopters on the bench with these supplies so they are not that weak...

**Comment by Ralim** [comment]
I would be inclined to pop the back off and inspect soldering on the DC jack. If that looks good, most likely its the power supply.
Quadcopers are designed to expect voltage sag and just wait for the supply to recover (or just run it overloaded).

**Comment by howels** [comment]
> I would be inclined to pop the back off and inspect soldering on the DC jack. If that looks good, most likely its the power supply. Quadcopers are designed to expect voltage sag and just wait for the supply to recover (or just run it overloaded).

Fair point, probably the voltage sags more than the iron expects and the voltage change is too much for the iron's input to tolerate. For now I'm just using the longer 8ohm tips, the iron reports an 80W draw anyway and heats up very quick plus I have a bunch of these tips.
