### ISSUE TITLE
MHP30 Accelerometer not Recognised

### ISSUE THREAD

**Issue by edrose** [Ralim/IronOS#1462]
**Describe the bug**
The accelerometer on my MHP30 is not recognised by IronOS. When scrolling through the debug menu, "ACC None" appears. "Move" is always 0.

The MHP30 does have an accelerometer, as the stock firmware uses it for topple detection.

**To Reproduce**
1. Load IronOS onto an MHP30
2. Press and hold button B to enter debug menu
3. Scroll through the menu. "ACC None" will be displayed and "Move" will always be 0.

**Expected behavior**
I expected IronOS to recognise the accelerometer in the MHP30.

**Details of your device:**
Device: MHP30
Release: 2.19.A3BBABC
Accelerometer: "None"

**Additional context**

**Comment by Ralim** [comment]
Could you try the 2.20 beta from the builds linked from [here](https://github.com/Ralim/IronOS/pull/1416).
Just in case this an accelerometer that is already enabled.

**Comment by River-b** [comment]
@edrose   if this ticket is resolved with new firmware could you close the ticket?

**Comment by discip** [comment]
@edrose
Are you still having issues with this?

**Comment by docgalaxyblock** [comment]
The accelerometer works fine on v2.20
*since the issuer is not responding over a week now...I guess you can close this*

**Comment by discip** [comment]
Closing this issue because the OP is not responding and no one else has reported comparable behavior.

**Comment by discip** [comment]
Closing this issue because the OP is not responding and no one else has reported comparable behavior.
