### ISSUE TITLE
About TS101 Software

### ISSUE THREAD

**Issue by Alsheikhy** [Ralim/IronOS#1470]
Hello, 

   I was looking to buy a soldering iron, after I saw that you have programed this TS100, I was interested to buy one of the best soldering irons out there, so I decided to buy the TS101, because it's the latest, also more powerful than the TS80.

I tried to find a software but I can't find one:).
Are you planning on doing one?

Sincerely,

**Comment by ImmortalScientist** [comment]
Duplicate of #1420 

Ralim seems to be working on it already :)

**Comment by Ralim** [comment]
Closing as this is a duplicate.
