### ISSUE TITLE
Random spikes in temperature to 473C on Pinecil V2

### ISSUE THREAD

**Issue by joric** [Ralim/IronOS#1485]
**Describe the bug**
There are random spikes in temperature up to 473 C (in fact it's almost always 473 C), not sure why. Noticed when temperature settings were are low, like 50-70C. They are visible on OLED display. Sometimes spike go to 471.

They really mess up the charting data I'm trying to record. I can try smoothing values with a kalman filter or something but that shouldn't come from the iron in the first place.

**To Reproduce**

1. Turn on the iron
2. Set temperature to 50C
3. Look at the OLED display, you will notice random spikes to 473 C.

**Expected behavior**
Temperature spikes to 473 C should not happen.

**Details of your device:**

 - Device: Pinecil V2
 - Release: 2.20 dev ([link](https://github.com/Ralim/IronOS/releases/tag/v2.20)), 2.20 BLE ([link](https://github.com/joric/IronOS/releases/tag/b6aaf30)). That DOES NOT happen on stock 2.18 ([link](https://github.com/joric/IronOS/releases/download/v2.18/pinecilv2-release-2.18.zip)).
 - Power adapter: QC (USB A to C) at 9V.

**Additional context**

It's NOT related to BLE, recent 2.20 dev release is also affected.

Video:

https://user-images.githubusercontent.com/852547/204616524-29db2ade-b6f4-4fc2-98fe-9d43ce23f379.mp4

Chart (https://joric.github.io/pinecil):

![image](https://user-images.githubusercontent.com/852547/204631781-4f393ef6-55d9-483a-8659-be5f59e47e75.png)

**Comment by Ralim** [comment]
Looks like ADC timing slipping.

Will test adding timing padding

**Comment by cohaolain** [comment]
Me and another discord user are now seeing this behaviour on some new Pinecil v2 units, which shipped with v2.20 build from 2022.12.13. Seems to not occur after downgrading to v2.18 .

**Comment by cohaolain** [comment]
I've found that these temperature reading spikes in v2.20 coincide with the tip being heated for slightly longer than normal, according to my power meter.
v2.20 :
![image](https://user-images.githubusercontent.com/20997804/212552287-dd03bc5a-4f54-4639-a8e4-772789b4fea5.png)
Video: https://photos.app.goo.gl/UUnb2tPmPnM5vL6f7 

Whereas in v2.18. these longer bursts don't seem to happen, nor do any temp reading spikes seem to occur. Temp regulation in general is more aggressive, it seems.
v2.18 :
![image](https://user-images.githubusercontent.com/20997804/212552409-5cbcbcc9-b9bd-4aea-ae8f-f1600f018d15.png)
Video: https://photos.app.goo.gl/xvQ7mrKuXa5DW6iE9

**Comment by cohaolain** [comment]
In these videos, the temperature is set to 200C.

The theory that this is related to the tip being powered slightly longer than expected would be backed up by the fact that in my video, after the temperature _appears_ to spike to 477C, the temperature reading appears to go to **210C** and cool down gradually to 200C again, as if it had just been heated too much slightly prior.
This _could_ be some kind of moving average filter, but the power meter _does_ show us heating a little longer than usual.

**Comment by cohaolain** [comment]
In @joric 's video, I'll also note that their temp reading briefly jumps to 52C after the 473C reading, might be the same thing happening with extra unintentional heating (but less pronounced due to their 9V power supply).

**Comment by cohaolain** [comment]
If this theory does pan out, it might warrant a change in the name of this ticket, or a new ticket - if this is just symptomatic of a more critical issue.

**Comment by River-b** [comment]
@joric and @cohaolain   if you tried the new beta and it fixed the  issue,  please close this  Ticket  :)

**Comment by cohaolain** [comment]
Personally think this can be closed 👍
