### ISSUE TITLE
TS100 firmware update 

### ISSUE THREAD

**Issue by grimpod1** [Ralim/IronOS#1497]
I have successfully updated my TS100 soldering iron with the TS100_UK.hex firmware file, which I assumed was English but the display I believe is in Russian! Have the firmware files been incorrectly labelled?

**Comment by discip** [comment]
@grimpod1
This is not Russian, it is Ukrainian.

You need the TS100_EN.hex if you want the English version.

**Comment by grimpod1** [comment]
I am so sorry I realized that and have already reprogrammed the TS100 to use the correct firmware thank you for your responses

**Comment by grimpod1** [comment]
User error I used the wrong hex file to program the firmware into the TS100
