### ISSUE TITLE
Pinecil V2 Windows 11 Issue

### ISSUE THREAD

**Issue by ckravig** [Ralim/IronOS#1519]
I am running Windows 11 on my desktop and when I go to plug the Pinecil V2 in to update the firmware I get the following error(s) 

**Windows:** 

![image](https://user-images.githubusercontent.com/15256405/210463947-90e4d735-6961-4282-9a5c-bb3f8bf98fbd.png)

**Device Manager shows:** 

![image](https://user-images.githubusercontent.com/15256405/210463995-9fb45e6c-d0dd-4ec2-8885-c861218b83ed.png)

**Powershell using blisp shows:**

![image](https://user-images.githubusercontent.com/15256405/210464024-1f55ef9d-5275-4420-8c4f-717bb7d555a3.png)

**Comment by Ralim** [comment]
I would be suspect of usb cable/hub combination first.
USB port is used to program it at the factory so the port should be fine; but you can try both flips of the USB-C to be sure.

**Comment by ckravig** [comment]
Okay, I will try flipping the USB-C first, and then some combinations of other cables and ports afterward. I am using the red 
USB-C to C cable from Pine64 plugged directly into a USB-C port on the back of my motherboard.

**Comment by ckravig** [comment]
I just tried flipping the cable, using another 2 different cables (C and A) along with trying a different computer that is running Windows 10. All of that resulted in the same error.

Any other advice?

**Comment by Ralim** [comment]
Try a different computer 🙃 
USB port would have been used at the factory; so _unlikely_ the port is damaged (hopefully).

**Comment by ckravig** [comment]
I did try another computer and it gave the same results. The Pinecil has no issues working as an iron as far as receiving power from the usb.

**Comment by Ralim** [comment]
You are making sure you are holding the rear button for the first ~10 seconds while you connect it (and screen should stay off/blank) ?

**Comment by ckravig** [comment]
> You are making sure you are holding the rear button for the first ~10 seconds while you connect it (and screen should stay off/blank) ?

That was it, I see in the wiki where I missed that step to hold down the [ - ] button. 

Thank you so much for the help!
