### ISSUE TITLE
Build with STM32 Workbench

### ISSUE THREAD

**Issue by TongweiRen** [Ralim/IronOS#1521]
Hi there,

I want to build IronOS by using STM32 Workbench Eclipse, but I didn't find `workspace` folder you mentioned in the previous related issues. What should I do for making it work?

Besides, I also tried the docker way, but when I ran build.sh in the docker container, there are errors:
```
Core/Drivers/USBPD.cpp:7:10: fatal error: fusb302b.h: No such file or directory
    7 | #include "fusb302b.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:516: Objects/TS80P/./Core/Drivers/USBPD.o] Error 1
make: *** Waiting for unfinished jobs....
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
Core/Threads/GUIThread.cpp:29:10: fatal error: pd.h: No such file or directory
   29 | #include "pd.h"
      |          ^~~~~~
compilation terminated.
make: *** [Makefile:516: Objects/TS80P/./Core/Threads/GUIThread.o] Error 1
```

Thanks for your help!

**Comment by Ralim** [comment]
>Besides, I also tried the docker way, but when I ran build.sh in the docker container, there are errors:

This is because you did not do a recursive clone.
Either do a recursive clone to get

STM32 Workbench / STMCubeIDE are no longer supported (that was _years ago_); as it only works for the OG TS100/TS80 but doesnt like to work with newer ones with clone chips _or_ with Pinecil devices.
