### ISSUE TITLE
What about GVDA GD300?

### ISSUE THREAD

**Issue by Kabron287** [Ralim/IronOS#1532]
https://www.gvda-instrument.com/soldering-station/usb-charger-65w-electric-soldering-iron-kit.html

**Comment by Ralim** [comment]
Are schematics open or reverse engineered already ?
What MCU and PD interface is used?

**Comment by Kabron287** [comment]
No info at the moment, but device looks very good.

**Comment by Ralim** [comment]
I'm not overly impressed, it looks like it's the old style tips and no EPR support. If schematics are available and it's an easy MCU to develop for I can have a poke but can't promise anything.

**Comment by Titanium-0neByte** [comment]
It would be great to see IronOS on this soldering iron 😁

**Comment by filimonic** [comment]
Agree, I'd be great to see IronOS there

**Comment by filimonic** [comment]
![image](https://user-images.githubusercontent.com/2893566/214652934-74582403-c570-43b1-b08e-e37c986f054d.png)
This is main MCU

Two other ICs are USB PD and mosfet
![image](https://user-images.githubusercontent.com/2893566/214653057-06b77aaf-7acb-48a0-8069-881c5d5de675.png)

![image](https://user-images.githubusercontent.com/2893566/214653224-0353838b-5e15-48d2-ba80-9a06b6457267.png)

**Comment by Ralim** [comment]
Yeah I have no idea what that main MCU is. Doesnt seem to have any manufacturer markings either.
Do these devices show up on usb when connected to a PC?

**Comment by Titanium0B** [comment]
Apparently, it is not displayed when connected to a PC (I don’t know because it hasn’t arrived to me yet), but the microcontroller can be STM8S103 or ATtiny2313 (SOP-20) can be different, but these are more likely

**Comment by BF3000** [comment]
Not a chance.
Gvda gd300 doesn't support firmware update.
There is another soldering iron for the same t65 tips called fnirsi hs-01, that one at least have the ability to update firmware.

**Comment by sameSEA** [comment]
Accordingly their web site GD300 supports firmware update:
[https://www.gvda-instrument.com/news/gvda-new-arrive-65w-mini-electric-soldering-ir-62926981.html](url)
_"It built-in smart MCU and acceleration semsor chip enable you to update the firmware or parameter setting via computer"_
