### ISSUE TITLE
screen is "messed up" with the detailed soldering screen

### ISSUE THREAD

**Issue by TomW1605** [Ralim/IronOS#1547]
**Describe the bug**
when the Pinecil goes to sleep after the timeout the sleeping screen is "messed up" and still shows the temp

**To Reproduce**
let the pinecil go to sleep while soldering with the detailed soldering screen

**Expected behavior**

should just say "Sleeping"

**Details of your device:**
 
 - Device: Pinecil V2
 - Release: 2.20.07D85C8
 - Power adapter being used: Anker Nano 2 with pine64 c-c cable

**Additional context**

for me this has reliably happened every time it sleeps. i have tried with the sleep timeout of 10 to 60secs. it goes away when you move the pinecil to wake it up

possibly related to #1417 

![IMG_8947](https://user-images.githubusercontent.com/17092573/215076077-5faaafb0-a800-455a-85e1-3869d6b4d23c.jpg)

**Comment by TomW1605** [comment]
didnt think to test this but it is not an issue when using the standard soldering screen

**Comment by discip** [comment]
Thank you for pointing that out.
Will fix. 😊
