### ISSUE TITLE
Expose   "Reset All Defaults"  for BLE usage

### ISSUE THREAD

**Issue by River-b** [Ralim/IronOS#1566]
**Is your feature request related to a problem? Please describe.**
For Builder555  effort  for BLE  settings changer for Pinecil V2  we  can not currently  use the BLE  to  select "Reset All to Defaults"   as builder555 notes in the below ticket,  that this is not exposed or they can't find it if it is.

https://github.com/builder555/pinecil-v2/issues/3#issuecomment-1419979263
**Describe the solution you'd like**
Please expose  this for BLE  from the Advanced Menu > reset all to defaults.
This would allow  people using the  newest BLE app to press one button on the browser screen to reset everything back to defaults.

![image](https://user-images.githubusercontent.com/97197236/217328465-ed85d9a8-fef3-490a-af3b-623e8cf83d25.png)

**Comment by builder555** [comment]
@Ralim can you let me know the ID of the characteristic(setting) for resetting to factory, and can I assume it'll require a `1` written to it? 
i'll add it to a branch, so it'll be ready when you release 2.21

**Comment by Ralim** [comment]
@builder555 

Put up my first ideas in #1567 if you want to have a look.

**Comment by builder555** [comment]
@Ralim i see all the settings shifted by 1, that was an exciting 15 seconds 😅

**Comment by Ralim** [comment]
I did note it in the PR that I set them back to being `0` based.
I think thats a better way to do it though; since then setting `0` on the firmware is also setting `0` on the BLE interface.

**Comment by builder555** [comment]
definitely better for consistency. i made a provision for backwards compatibility anyway, so it won't be an issue

**Comment by Ralim** [comment]
Fantastic; thank you :)
