### ISSUE TITLE
Pinecil v2: Consider changing characteristics UUIDs in BLE services

### ISSUE THREAD

**Issue by marcnause** [Ralim/IronOS#1569]
The UUIDs of characteristics in https://github.com/Ralim/IronOS/blob/dev/source/Core/BSP/Pinecilv2/ble_characteristics.h are only unique in the scope of the different services. They are not unique in the scope of the whole device.

Also the UUIDs are 16 bit UUIDs which according to https://www.oreilly.com/library/view/getting-started-with/9781491900550/ch04.html (below headline **UUID**) can be used only for characteristics which are defined in the Bluetooth specification. (At least that's how I understood it, alas I am no BLE expert.)

For this reason I propose to at least consider changing the UUIDs so that the base UUID is the UUID of the respective service (128-bit UUID) as described in https://devzone.nordicsemi.com/guides/short-range-guides/b/bluetooth-low-energy/posts/ble-services-a-beginners-tutorial (below headline **Universally Unique ID (UUID)**)

Example:

New UUID for `BT_UUID_CHAR_BLE_LIVE_LIVE_TEMP`: `d85e0001-168e-4a71-affd-33e27f9bc533`

I know that there are at least 2 clients using the Pinecil BTL services already, but since BLE support is still fairly new and there are still new features planned for IronOS v2.21, maybe now  is the time to discuss this issue before more people rely on the characteristics UUIDs.

**Comment by builder555** [comment]
wouldn't be a big deal to change for PineSAM: https://github.com/builder555/PineSAM/blob/master/backend/setting_names_map.py
