### ISSUE TITLE
MHP30 - Idle bug

### ISSUE THREAD

**Issue by docgalaxyblock** [Ralim/IronOS#1570]
*A video shows more then 100 words can describe*

<video src="https://user-images.githubusercontent.com/21227087/219048616-b247806f-5609-4847-b620-61f5d1a5854c.mp4"></video>

two issues:
- **A)** display goes of, starts flashing green, no heating
- **B)** sometimes it did not let me into heating mode again

**To Reproduce**
Just leave it on
  - idle at the menu (I guess it is an idle bug since it mostly happens after exactly 1min here)
  - heating *(for the video test at 40/50°C)* for a while
sometimes it happens after eg 2min sometimes after eg 13min

MHP30 - 2.20.14DAF70
Power adapter: QC92 *(comes with the NovelLive full kit on Ali)*
*Not sure if this is an accelerometer related issue:* SC7A20

Tried both DE and EN with reset

**Comment by Ralim** [comment]
You need to use a PD power adaptor for full functionality; heating on 5V just doesnt work and causes brownouts that cause mis-behaviour of the unit.

**Comment by docgalaxyblock** [comment]
@Ralim I used 5V only for the video

> Power adapter: QC92 (comes with the NovelLive full kit on Ali)
That is the PSU I have and it happend while I want to solder a pcb
