### ISSUE TITLE
cloned STM32 Chips?

### ISSUE THREAD

**Issue by violavon** [Ralim/IronOS#1574]
What is "cloned STM32 Chips"?

From README:

|   Device   | DC  | QC  | PD  | EPR | BLE | Battery | Recommended |
| :--------: | :-: | :-: | :-: | :-: | :-: | :-----: | :---------: |
|   MHP30    | ❌  | ❌  | ✔️  | ❌  | ❌  |   ❌    |     ✔️      |
| Pinecil V1 | ✔️  | ✔️  | ✔️  | ❌  | ❌  |   ✔️    |     ✔️      |
| Pinecil V2 | ✔️  | ✔️  | ✔️  | ✔️  | ✔️  |   ✔️    |     ✔️      |
|   TS80P    | ❌  | ✔️  | ✔️  | ❌  | ❌  |   ✔️    |     ✔️      |
|   TS100    | ✔️  | ❌  | ❌  | ❌  | ❌  |   ✔️    |     ❌      |
|    TS80    | ❌  | ✔️  | ❌  | ❌  | ❌  |   ✔️    |     ❌      |

\*Please note that Miniware started shipping TS100's using cloned STM32 Chips. While these do work with IronOS, their DFU bootloader works terribly, and it is hard to get it to successfully flash larger firmware images like IronOS without timing out. This is the main reason why the TS100 is **_no longer recommended_**.

**Comment by Ralim** [comment]
Chips made by a manufacturer other than STMicroelectronics that try and implement their API but often do so poorly.
These units also have a large number of quirks that Miniware's bootloader does not work around correctly; so programming larger firmware files (such as IronOS) is a painful experience.

A place to start for information on these would be here: https://hackaday.com/2020/10/22/stm32-clones-the-good-the-bad-and-the-ugly/
