### ISSUE TITLE
Support for Quick 861DW hot air gun

### ISSUE THREAD

**Issue by violavon** [Ralim/IronOS#1580]
Could we bring support for Quick 861DW hot air gun? @VeryFastSnail has done a lot of work on this (schematics and firmware from scratch) and it would be great if we could use them to bring support for Quick 861DW to IronOS.

https://github.com/VeryFastSnail/Quick861dw

**Comment by Ralim** [comment]
It looks like this hardware does not meet minimum requirements of
- Arm Cortex M0 or faster
- 64k of flash or higher
- 16k of ram or higher

**Comment by Ralim** [comment]
If someone wanted to make a PR I would be very highly likely to merge it in; but I have zero desire to work with or support atmel parts these days.
