### ISSUE TITLE
Why TS80 isn't "recommended"?

### ISSUE THREAD

**Issue by violavon** [Ralim/IronOS#1586]
Why TS80 isn't "recommended"?

**Comment by Ralim** [comment]
Completely replaced by the TS80P and discontinued

**Comment by violavon** [comment]
Discontinued? https://www.miniware.com.cn/product/ts80-soldering-iron-more/

**Comment by Ralim** [comment]
Yes it may come as a shock, but production ramped down a long time ago and it's just existing stock clearing the system.

I marked it not recommended being optimistic that people might pause and buy the far superior TS80P instead

**Comment by violavon** [comment]
Okay, but does IronOS work as well with TS80 as with TS80P? Nothing like with TS100 and STM32 clones?

**Comment by Ralim** [comment]
To the best of my knowledge yes, but that doesn't change it from being a no-longer-reccomended device.

**Comment by violavon** [comment]
Hmm, then I feel we shouldn't be recommending anything on IronOS. I understand if there is something like TS100 and STM32 clones, but otherwise no.

**Comment by Ralim** [comment]
I don't follow your logic sadly.

The recommendation is for buying, not for using ironos.

**Comment by violavon** [comment]
In that context, it affects more the status of the support.

**Comment by Ralim** [comment]
Would you prefer the Reccomended column be renamed to something else to make it clearer?
Do you have suggestions?

**Comment by DjordjeMandic** [comment]
Maybe something like #1588 ?

**Comment by Ralim** [comment]
Sounds good
