### ISSUE TITLE
Pinecil v2 default configuration temperature bug

### ISSUE THREAD

**Issue by mutx** [Ralim/IronOS#1624]
In the [Pinecil v2 configuration header](https://github.com/Ralim/IronOS/blob/cae3ac93fd2476c17b8edd14da0bb44401c7d95c/source/Core/BSP/Pinecilv2/configuration.h) the MIN_TEMP_F and MIN_TEMP_C are not equivalent.

MIN_TEMP_F should be 50 (10 C), not 60.

Additionally, setting the temp to 10 Celsius and then switching units to Fahrenheit will set the temp to 50 Fahrenheit (even though the minimum is 60). Pressing the increase button will reset it to 60 Fahrenheit.

**Comment by River-Mochi** [comment]
![image](https://user-images.githubusercontent.com/97197236/225128838-976aced5-5e98-442e-ada4-f9690c2f52bd.png)

**Comment by discip** [comment]
fixed by #1625
