### ISSUE TITLE
IronOS Firmware update fails repeatedly on HP Pavilion DV7 Laptop

### ISSUE THREAD

**Issue by Stennje** [Ralim/IronOS#1629]
Just an FYI in case you experience something like these odd failures to flash......

Attempting to update my TS100 clone Sequre SQ-001 to 2.20 IronOS (it has always worked before on the SQ-001)  failed repeatedly, sometimes with SQ-001 "USB drive" appearing momentarily, then disappearing as I was copying HEX file over.....even though "DPU 3.45" still appeared on iron's display.  Attempts to copy file repeatedly failed, sometimes with "ERR" copies showing on iron when iron remained in Drive List, other times iron not remaining in drive list after about 5 seconds.  Tried latest original SEQURE 3.0 FW, and Miniware TS100 2.20, all experiencing vanishing drive phenomenon or "failure to copy file" messages.  Thought maybe caused by Avast anti-virus, so tried disabling shields temporarily (no difference) and also tried allowing Avast to scan iron, thinking when I canceled it's automatic scan that maybe Avast was blocking access....no success here either.

As IronOS docs direct "If it fails, just try again," I kept going about 6 or 7 times, but repeated failures (with those varying results) finally resulted in what seemed to be a "bricked" (electrically dead) SQ-001 / TS100....even plugging directly into DC supply with USB disconnected resulted in dead iron, it would not power up.

This was on an old HP Pavilion DV7-4153CL running Win 10 Pro 22H2.

So, as a somewhat desperate last-resort, moved my dead iron to my full-size tower desktop PC running a Ryzen CPU and Win10 Pro 21H2 on an MSI MS-7A34 motherboard with USB 3.0, and repeated process, first with latest SEQURE 3.0 firmware.......which immediately worked, iron booted properly !

After digging around in SEQURE firmware for a while, confirming all was well, I attempted IronOS 2.20 flash....which ALSO worked !
My iron remained in my Drive List consistently and I had no problem copying either FW file, SEQURE or IronOS.

There's NO malfunction or flakiness of my USB ports or any other hardware performance of my old HP Pavilion laptop....

... so I suspect the issue is the limited current output capability of some laptop USB ports,  only designed and capable of powering low-power devices like USB flash  memory sticks, but maybe not quite enough for powering electronic devices like a soldering iron with an LCD display. The limited USB current output would explain the intermittent presence of the iron as an accessible "Drive." 

If it's not that, I'm mystified,....but as they say..."All's well that ends well,"  so try a REAL PC if you have trouble flashing your iron using a laptop.  :)

**Comment by Ralim** [comment]
I suspect this is the issue that has been posted about a lot with the "fake USB drive" DFU bootloaders; where the exact software on the host computer (what is installed & what is running) can impact this.

Sadly though, fixing this is out of scope until they release the code as open source.
