### ISSUE TITLE
Add Bluetooth Icon to Pinecil V2 Firmware 

### ISSUE THREAD

**Issue by River-Mochi** [Ralim/IronOS#1640]
**Is your feature request related to a problem? Please describe.**

- Pinecil V2  Only. 
- Add this BLE  bluetooth  icon to  the Advanced menu

![image](https://user-images.githubusercontent.com/97197236/229117818-3693f6c8-afc4-430f-b4f0-ec89e65a0774.png)

**Describe the solution you'd like**
- Just  this icon and the word  Bluetooth   or if that doesn't fit  then this Icon and word BLE.
- Only need to implement this for Pinecil V2  and no other iron as no other  Iron even needs a BLE  Enable category.
- there is a lot of memory space in V2 and it's the only one that supports  Bluetooth.

thanks

**Comment by Ralim** [comment]
I'm inclined to lean towards keeping the menus text based; as it's more uniform to the other menus, and it keeps things simpler to avoid having custom draw handling where we can.

What's wrong with having the menu called Bluetooth, and in the help text saying it enables BLE?

**Comment by discip** [comment]
I am sorry to disappoint you, but the same applies to the expression itself as to the symbol.
**`Bluetooth`** is unique in all languages.

**Comment by discip** [comment]
Closing as the main developer is inclined to 
> keeping the menus text based
