### ISSUE TITLE
BLE: is more unique names gone from Pinecil V2?

### ISSUE THREAD

**Issue by River-Mochi** [Ralim/IronOS#1655]
**Describe the bug**

BLE "more" unique name is no longer showing up in BLE apps for Pinecil V2.
"None" in this screenshot used to have the "more unique"  name. This is confirmed for PineSAM and also Tom's ESPhome app. 

![image](https://user-images.githubusercontent.com/97197236/230604986-a937b834-ec0d-483a-8c33-5220d8f60ae0.png)

using the newest  2.21 pre-realease beta, and one from yesterday.

**Comment by Ralim** [comment]
Names work perfectly fine for me here scanning with laptop or phone. Also there is no way for the C code to generate the name `Pinecil-None`; the `None` makes me highly suspect your looking at a bug in the app your using to connect to the device.

**Comment by River-Mochi** [comment]
> Names work perfectly fine for me here scanning with laptop or phone. Also there is no way for the C code to generate the name `Pinecil-None`; the `None` makes me highly suspect your looking at a bug in the app your using to connect to the device.

none is from our side yes.  Tom is also having issues getting the  unique name in his ESPhome app  so I was wondering it  something changed.

**Comment by River-Mochi** [comment]
Closing ticket,  all good now. 
issue on pineSAM  side  is  UUID  was in more than one place in code and one of the hardcoded variables was missed.

![image](https://user-images.githubusercontent.com/97197236/230633083-be35d8f0-9d76-4d53-94f1-89fb8819c59d.png)
