### ISSUE TITLE
Quick Start guide bluetooth communication with IronOS.

### ISSUE THREAD

**Issue by River-Mochi** [Ralim/IronOS#1656]
I'd like to write a Quick Start Bluetooth LE article to help people get started connecting bluetooth Apps to IronOS. 
basic things they need so they don't waste time hunting around for it.  I would provide things such as a link to a list of all UUID/names needed.  Probably going to be a shorter stub for now.

I'm not an expert in this, and hopefully Ralim or some of the people working on BLE apps now will add a little more if I start it. 

Goal is to 
(a)  prevent some tickets and questions  to IronOS  if  the basics are covered.
(b) encourage more people to make BLE apps to work with IronOS. 
(c) give some resources if they get stuck.

**Comment by warlock31415** [comment]
+1 for guide. Was thinking of making a stand for the Pinecilv2 with a oled display to essentially mirror the on board screen. This can be done over the Debug info being spit out of the uart but I also wanted to add temp control using an encoder. Can't do that over uart without adding a bunch of command parsing functions over uart.

My next thought was PineSam already has control with BLE so maybe can make something with a NRF52. So documentation would be highly appreciated.

**Comment by River-Mochi** [comment]
waiting for Ralim to approve before I start it in IronOS  docs.

**Comment by River-Mochi** [comment]
> +1 for guide. Was thinking of making a stand for the Pinecilv2 with a oled display to essentially mirror the on board screen. This can be done over the Debug info being spit out of the uart but I also wanted to add temp control using an encoder. Can't do that over uart without adding a bunch of command parsing functions over uart.
> 
> My next thought was PineSam already has control with BLE so maybe can make something with a NRF52. So documentation would be highly appreciated.

Look into Tom's project also  for this.  
He is sending bLE data from Pinecil to ESP32, and then that is using Home assist. and then  he has a DIY fan  which automatically comes on if Pinecil is "heating up".    And he is now also trying to implement some of the settings features   that are in PineSAM app.  I added all project  to Development in[ Pinecil wiki here](https://wiki.pine64.org/wiki/Pinecil#Development_Projects).

**Comment by River-Mochi** [comment]
@warlock31415  - could also right now use an old android/iphone with PineSAM right now and show all pinecil display too?  that is what I do, old phone in phone stand which I can also tap on screen to change Pinecil settings.

-  I personally tested the buttons on phones to make sure pinesam buttons made big enough to work even if you have nitrile gloves on while soldering. much better accessibility for people with vision issues so they don't have to keep switching from magnifying glasses/lens to  reading glasses while soldering.

**Comment by warlock31415** [comment]
@River-Mochi It looks like Home assistant does all the heavy lifting on the ESP32 project. I just want something simplistic. Something that mimics weller base stations. I also want to get into learning the nordic dev system

**Comment by aguilaair** [comment]
I am working on a companion app for phones currently: https://github.com/aguilaair/IronOS-Companion

Currently connects and visualizes data, next step is sending commands to the iron

![image](https://user-images.githubusercontent.com/29983481/236954504-fa9f6f98-64e0-4b86-87c2-6e0eec82d760.png)

**Comment by aguilaair** [comment]
Hey @gamelaster will do! I don't think it's fully ready yet to be pushed to the app stores, still need a couple of weeks to finish it up :)

**Comment by Ralim** [comment]
Correct and deliberate for safety at the moment.

**Comment by gamelaster** [comment]
@Ralim & @aguilaair I think STOP command would be useful and not that big safety risk, although, START might be, but that might be solved by showing some prompt, so user actually needs to confirm the START with button (but that misses the whole point of having it wireless).

**Comment by agibson2** [comment]
This app looks amazing so far.  Was it ever pushed to the apple store?

**Comment by gamelaster** [comment]
It will be hopefully @agibson2
