### ISSUE TITLE
Possibly a typo in 128-bit BLE UUIDs

### ISSUE THREAD

**Issue by joric** [Ralim/IronOS#1659]
@Ralim I have updated my GUI tool yesterday and it works but I'm just wondering why settings UUID start from f6d8 but characteristics start from f6d7. is it intentional or is it a typo? Top 4 digits for BULK data and BULK data UUIDs match.

From https://github.com/joric/pinecil (it works with the latest 2.21, but it's kind of strange).
```js
  BT_UUID_SVC_BULK_DATA                      = '9eae1000-9d0d-48c5-aa55-33e27f9bc533'; // bulk service
  BT_UUID_CHAR_BLE_BULK_LIVE_DATA              = '9eae1001-9d0d-48c5-aa55-33e27f9bc533'; // <-- matches service UUID

  BT_UUID_SVC_SETTINGS_DATA                  = 'f6d80000-5a10-4eba-aa55-33e27f9bc533'; // settings service
  BT_UUID_CHAR_BLE_SETTINGS_VALUE_SAVE       = 'f6d7ffff-5a10-4eba-aa55-33e27f9bc533'; // <-- does not start from f6d8
  BT_UUID_CHAR_BLE_SETTINGS_VALUE_SETPOINT   = 'f6d70000-5a10-4eba-aa55-33e27f9bc533'; // <-- does not start from f6d8
```

File in question: [source/Core/BSP/Pinecilv2/ble_characteristics.h](https://github.com/Ralim/IronOS/blob/422b5b7563536a7783dfeb688614897f933f5e00/source/Core/BSP/Pinecilv2/ble_characteristics.h#L24):

```cpp
// f6d75f91-5a10-4eba-a233-47d3f26a907f
#define BT_UUID_SVC_SETTINGS_DATA BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0xf6d80000, 0x5a10, 0x4eba, 0xAA55, 0x33e27f9bc533))
...
#define BT_UUID_CHAR_BLE_SETTINGS_VALUE_SAVE  BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0xf6d7FFFF, 0x5a10, 0x4eba, 0xAA55, 0x33e27f9bc533))
#define BT_UUID_CHAR_BLE_SETTINGS_VALUE_RESET BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0xf6d7FFFE, 0x5a10, 0x4eba, 0xAA55, 0x33e27f9bc533))
#define BT_UUID_CHAR_BLE_SETTINGS_VALUE_0     BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0xf6d70000, 0x5a10, 0x4eba, 0xAA55, 0x33e27f9bc533))
#define BT_UUID_CHAR_BLE_SETTINGS_VALUE_1     BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0xf6d70001, 0x5a10, 0x4eba, 0xAA55, 0x33e27f9bc533))
...
```
Note there's also a comment with an old UUID `// f6d75f91-5a10-4eba-a233-47d3f26a907f` why it's there? Just for history?

**Comment by Ralim** [comment]
>Note there's also a comment with an old UUID // f6d75f91-5a10-4eba-a233-47d3f26a907f why it's there? Just for history?
yeah, will probably drop that

I split the settings to be in a different base uuid just in case we end up with a larger set of them; as its most likely to grow and get messy. I want to automate the creation of the ble uuid table for the settings too but it hasnt yet worked for me.

**Comment by joric** [comment]
@Ralim when it was standard UUDS I just used BluetoothUUID.canonicalUUID(1); to define a characteristic in js so maybe just use a function, those text labels eat an awful lot of space.
