### ISSUE TITLE
MHP30 adressable LED only shows green channel

### ISSUE THREAD

**Issue by codingcatgirl** [Ralim/IronOS#1671]
**Describe the bug**
The Code suggests that the MHP30 shouuld show different LED colors during operation. However, the only colors i see while using it are green, dark green (when it should be orange) and off (when it should be red). It looks like adressing the LED doesn't work.

**Comment by Ralim** [comment]
For both of my devices here it is showing R/G/B as expected on the latest release :/
Can you confirm that your led is fully operational via the factory firmware?
Also any chance of a photo of the led (wondering if they have changed it)

**Comment by codingcatgirl** [comment]
What i can say is that it definitely lights up in blue in the DFU mode. Not sure if i've seen red, i didn't pay *that* close attention to it since i got it 2 days ago :D Are there any instructions how to best open up this thing? then i'll take a look

**Comment by Ralim** [comment]
The led is is under the hot top so can just pull up on the heater pad and it should neatly pop off the base (its on pins).

Okay so definitely sounds like something is going wrong somewhere hmm.

**Comment by codingcatgirl** [comment]
Thanks, that was almost too easy.

Anyway, the LED does look like then one that has been indentified before though
![image](https://user-images.githubusercontent.com/3868507/233871794-5a36f9d4-b5d4-4c8f-882b-7197cd5f233e.png)

**Comment by codingcatgirl** [comment]
I've set it to white and it is cyan now. Hm.

**Comment by Ralim** [comment]
Definitely a new revision of that top board compared to mine.
Gotta wonder what changed lol.

Maybe try adjusting the timing values a bit in the driver code? Could be on the edge for the bit timings for your unit?

**Comment by codingcatgirl** [comment]
I've flashed the original firmware again. It seems that the original firmware can't show any red either. So i have to assume that my unit is either broken… or that the new hardware revision does have some difference and the firmware they have available for download isn't correct for my hardware revision. Wish i would have paid more attention to my first test with the stock firmware. The latter would be better of course, but it might just be time to see if i can swap the LED, unless anyone else will show up with the same problem here.

**Comment by Ralim** [comment]
Damn, I was really hoping it wasnt a damaged led.
On the bright side its not stupid hard to replace at a guess.

In terms of timings; its all the asm crud in https://github.com/Ralim/IronOS/blob/dev/source/Core/Drivers/WS2812.h

**Comment by codingcatgirl** [comment]
> On the bright side its not stupid hard to replace at a guess.

Yeah especially since i now have a hot plate… ……… oh

**Comment by discip** [comment]
@codingcatgirl
Did you manage to solve this issue?
If so, please don't forget to close this. 😊

**Comment by codingcatgirl** [comment]
The issue seems to be hardware-related, so i'm gonna glose this, yep.

**Comment by codingcatgirl** [comment]
Do you see any other colors with the official firmware? If not, you just have the same broken LED as me and this is not a firmware issue.
