### ISSUE TITLE
TS101 - German firmware

### ISSUE THREAD

**Issue by comtechnik** [Ralim/IronOS#1722]
Is there a German firmware for the TS101?

**Comment by comtechnik** [comment]
Is there a time when this will come?

**Comment by gamelaster** [comment]
TS101 support was merged week ago, so maybe soon, although, there is no certain time when major release with TS101 will be released.

**Comment by comtechnik** [comment]
Thank you for your quick response. Hope it comes soon :-)

**Comment by discip** [comment]
Closing, as this question was answered! 😊
