### ISSUE TITLE
compile instruction

### ISSUE THREAD

**Issue by He1my** [Ralim/IronOS#1724]
where can I find compiling instructions under Linux?

**Comment by StevenSeifried** [comment]
1. Install `git`, `docker` and `docker-compose`
2. Start `docker`
3. `git clone --recursive --branch v2.21 https://github.com/Ralim/IronOS.git`
4. `cd IronOS`
5. `sh start_dev.sh`
6. `cd source/source`

Examples:
- For Pinecil v1: `./build.sh -l EN -m Pinecil `
- For Pinecil v2: `./build.sh -l EN -m Pinecilv2`
- For TS100: `./build.sh -l EN -m TS100`
- For TS80: `./build.sh -l EN -m TS80`
- For TS80P: `./build.sh -l EN -m TS80P`
- For MHP30: `./build.sh -l EN -m MHP30`
[Here](https://ralim.github.io/IronOS/Development/#examples) you can find other examples


Firmware files are in `source/Hexfile`
