### ISSUE TITLE
compilation error Pinecilv2 help

### ISSUE THREAD

**Issue by goga1978** [Ralim/IronOS#1825]
HI.

c1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
In file included from Core/Threads/OperatingModes/SolderingProfile.cpp:2:
Core/Threads/OperatingModes/OperatingModes.h:23:10: fatal error: pd.h: No such file or directory
   23 | #include "pd.h"
      |          ^~~~~~
compilation terminated.
make[1]: *** [Makefile:720: Objects/Pinecilv2/./Core/Threads/OperatingModes/SolderingProfile.o] ERROR 1
make[1]: выход из каталога «/home/goga/blis/IronOS/source»
make: *** [Makefile:228: firmware-EN] ERROR 2
goga@goga-Aspire-E1-572G:~/blis/IronOS$ make firmware-EN model=Pinecilv2
make  -C source/  firmware-EN
make[1]: вход в каталог «/home/goga/blis/IronOS/source»
Building for Pine64 Pinecilv2 
 
cc1plus: warning: ./Core/Drivers/usb-pd/include: No such file or directory [-Wmissing-include-dirs]
In file included from Core/Threads/OperatingModes/SolderingProfile.cpp:2:
Core/Threads/OperatingModes/OperatingModes.h:23:10: fatal error: pd.h: No such file or directory
   23 | #include "pd.h"
      |          ^~~~~~
compilation terminated.
make[1]: *** [Makefile:720: Objects/Pinecilv2/./Core/Threads/OperatingModes/SolderingProfile.o] ERROR 1
make[1]: выход из каталога «/home/goga/blis/IronOS/source»
make: *** [Makefile:228: firmware-EN] ERROR 2

![Kazam_screenshot_00279](https://github.com/Ralim/IronOS/assets/31812770/6ef5e4a2-cf7b-4bc5-929f-0388cbb850ca)

**Comment by StevenSeifried** [comment]
Did you used `git clone` with `--recursive` to clone the repository? Otherwise the submodules are not included

**Comment by goga1978** [comment]
Thank you very much. Everything worked.
git clone --recursive https://github.com/Ralim/IronOS.git

**Comment by discip** [comment]
@goga1978
If this is solved, please do not forget to close. 😊

Thank you!
