### ISSUE TITLE
New MHP30 [Hver:1.60] troubles.

### ISSUE THREAD

**Issue by ratmole** [Ralim/IronOS#1837]
### Discussed in https://github.com/Ralim/IronOS/discussions/1812

Opening this as an issue, as it seems that many ppl having this exact problem, and maybe not see it on the discussions. Thanks

<div type='discussions-op-text'>

<sup>Originally posted by **gossamer2** September  7, 2023</sup>
I just received my new MHP30. I tried it once and it worked fine with the factory firmware. I found this IronOS firmware and wanted to give it a try. I tried 2.22 and then 2.21. When it boots up, the light is yellow. On the left of the display, there is a squiggly line over an exclamation mark. On the right is the settings icon with a 5 next to it. Is there something i need to do first?

I'm using the original power supply with original USB-C cable.

The original firmware on it was 2.11, HW 1.60

Unfortunately, I can't even find the original factory firmware as it looks like the miniware site is down. Argh!</div>

**Comment by Ralim** [comment]
I'm well aware of this; please dont spam extra noise 🙇🏼 Every _single_ action on here sends me an email.
Please understand that time is exceptionally limited, and I havent had time to sit down and look at what could have change; so as I've had nothing new to add, I havent yet commented.
