### ISSUE TITLE
Problem In Understanding Language Code UK

### ISSUE THREAD

**Issue by onxblog** [Ralim/IronOS#1876]
We currently have a translation file named translation_UK.json, which is intended for Ukrainian language content. However, the abbreviation 'UK' is incorrect; it typically refers to the United Kingdom. Instead, we should use 'UA' to represent Ukraine. 'UA' is the appropriate abbreviation, akin to the domain zone 'UA', and universally recognized by software applications to denote content related to Ukraine. Therefore, we need to replace all instances of 'UK' with 'UA'.

**Comment by agatti** [comment]
@onxblog I believe they follow ISO-639 language codes, as per https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=uk

**Comment by discip** [comment]
@onxblog
Please refer to the following PR for reference: #407

**Comment by onxblog** [comment]
Oh, I see. In my opinion, it would be better to use ISO 639-2 for this purpose.
In this case, Windows utilizes ISO 639-2, which focuses on languages rather than countries, making it more universally understood.
The first thing that comes to mind when seeing two letters like UK is the top-level domain.

**Comment by ia** [comment]
Just for the information: as far as I understand, even in [_ISO 639-2_](https://www.loc.gov/standards/iso639-2/php/code_list.php) it's not `ua` either.

**Comment by ia** [comment]
So, in case if no one's mind, I guess this should be closed.
Key takeaway: [in discussion's context] `ua` is _internet_ domain, `uk` is _language_ code.
I perfectly understand that it may be counter-intuitive but that's how it is according to the standards.
