### ISSUE TITLE
L245p usb soldering iron

### ISSUE THREAD

**Issue by AbdurRoufBusiness** [Ralim/IronOS#1910]
Recently bought a usb soldering iron that uses c245 style tips i was thinking if it is possible to install iron os on it providing some pictures the mcu has it’s makings removed so didn’t took a close up of it and seems like it has a uart port 
Thank you
![IMG_2132](https://github.com/Ralim/IronOS/assets/132583428/e9bcf224-a613-4c74-8f4a-83270b347d11)
![IMG_2133](https://github.com/Ralim/IronOS/assets/132583428/6413623c-3932-4b50-9c49-c62ebe6132f3)
![IMG_2134](https://github.com/Ralim/IronOS/assets/132583428/8cd4b454-4ed3-4265-a131-887db0541239)

**Comment by ia** [comment]
> if it is possible to install iron os on it

The short answer is: _unfortunately, no_.

Please, look at [the very first table in this document](https://github.com/Ralim/IronOS/blob/dev/README.md) to check which devices are _supported currently_.

Thanks.

**Comment by Ralim** [comment]
[Documented in the main documentation is the requirements for IronOS](https://ralim.github.io/IronOS/PortingToNewDevice/).

Realistically there are so many cheap cost-cut irons coming out of China I dont have the time to look into each one.
