### ISSUE TITLE
Support for the power supply "SuperDart" standard

### ISSUE THREAD

**Issue by UZver24** [Ralim/IronOS#1921]
I have a power supply from a Realme phone.
When trying to use it, Pine 64 reports a low voltage, although the power supply should provide the necessary power and voltage. Is it possible to supplement the firmware for compatibility with the power supply?
![image](https://github.com/Ralim/IronOS/assets/171164035/829e5358-8b63-4834-87c8-362c8d2caaac)
![image](https://github.com/Ralim/IronOS/assets/171164035/53a8fed7-d458-4c26-8211-9e66c86e13cd)

**Comment by Ralim** [comment]
Hello,
As far as I can find this protocol isn't open source so I can't check if the hardware could implement it.

Secondly, it is not high enough voltage. This is a low voltage high current supply. Where as we want higher voltages. This unit doesn't appear to be capable of outputting >12V which is the minimum usable voltage.
