### ISSUE TITLE
Uninstall IronOS firmware?

### ISSUE THREAD

**Issue by jockethebastard** [Ralim/IronOS#1971]
Is there a way to go back to original firmware. I'm having trouble where it won't recognize tips and it says it's over 400 degrees just when I put it in. After a while it just won't recognize it. 
Also, I'm kinda tired of the "small screen".

**Comment by StevenSeifried** [comment]
Which device? If you have the original firmware available, you can flash it over the same way as you flashed IronOS onto it.

(I tested it myself yesterday with my TS101)
