### ISSUE TITLE
TS80P reading room temperature too high after upgrade to IronOS 2.22

### ISSUE THREAD

**Issue by nikolasgd** [Ralim/IronOS#1986]
My TS80P with IronOS 2.22E.C308FE8C reports a room temperature of around 170 degrees Celsius in idle mode.

For reproducing both handle and tips are at room temperature, around 21 degrees C. I have calibrated the iron and tried multiple tips (and power adapters just to make sure), all the same.

Values reported in debug menu are: RTip at ~ 1500 and CHan at ~ 170.

So from my understanding, CHan is the PCB temperature sensor reading in Celsius x 10? Seems reasonable in tolerance.

Reported temperature in idle main menu seems to be exactly the CHan value (without the decimal fraction part). So a CHan value of 170.1 will report tip temperature of 170 degrees celcius.

Since both Rtip and CHan values are in expected range, this must a software bug?

Thanks for looking into it. I really appreciate the work and dedication you put into this.

**Comment by nikolasgd** [comment]
Just to confirm. This does not occur in the previous release IronOS V2.21. I have switched back to this version for now, as PD is also not working anymore in the latest release.

**Comment by discip** [comment]
Have you tried calibrating the device according to this documentation?
Please follow the instructions carefully, especially those stating **_to wait_**. 😊

**Comment by nikolasgd** [comment]
Definitely not a calibration issue. Temperature is reported correctly after switching back to IronOS 2.21

**Comment by discip** [comment]
Oh, sorry, I forgot to put in the link to the documentation and missed the part in the initial post that **literally** states that you already calibrated the iron. 🤦🏻 😅

> Definitely not a calibration issue.

> I followed these instructions:

That's interesting.
I also own a **TS80P** and it works as expected with the latest firmware.

Maybe your device uses a **GD** chip instead of a **STM** one?

**Comment by nikolasgd** [comment]
I will check tomorrow which chip is used. Can I find this info in the debug menu or only by looking at the pcb?

**Comment by discip** [comment]
Unfortunately you would need to open the device.

**Comment by nikolasgd** [comment]
![image](https://github.com/user-attachments/assets/8c773a8a-499e-4c64-aa95-df63007302bf)

So the chip on the upper side of the PCB is an STM32.

**Comment by discip** [comment]
@nikolasgd
Have you tried cleaning the contacts of the jack and plug with **_isopropyl alcohol_**?

@Ralim
Any idea what could be causing this behavior?

**Comment by nikolasgd** [comment]
> @nikolasgd Have you tried cleaning the contacts of the jack and plug with **_isopropyl alcohol_**?

I haven't tried that, as the problem can be reproduced with all of my 5 or so tips. And the temperature reads perfectly fine in IronOS 2.21.

**Comment by Ralim** [comment]
Eugh what a mess.

I have a suspicion of the cause on this, we had some issues with analog mode on clone chips.
Possibly this is causing an issue on this legit STM32.

I'll try and make a test image for you when I get time (nag me in 24 hours if I dont post one)

**Comment by nikolasgd** [comment]
Ready to test the image whenever you are! @Ralim

**Comment by Ralim** [comment]
Apologies on the delay,
Turned out to not be what I was first suspect of (turns out that change was only done for MHP30)

But can try the same change.
Can you try from the TS80P files [from here](https://github.com/Ralim/IronOS/actions/runs/11720606218) (download at the bottom of the page)

**Comment by nikolasgd** [comment]
Can confirm! Both tip temperature as well as PD do seem to be working alright in my quick test.

**Comment by discip** [comment]
> Can you try from the TS80P files [from here](https://github.com/Ralim/IronOS/actions/runs/11720606218) (download at the bottom of the page)

This seems to have solved the issue as my iron still reads the correct temperature and OP states that his iron does the same. 😊

So, I hereby declare that the issue is solved.
