### ISSUE TITLE
TS101 Screen Brightness Control 

### ISSUE THREAD

**Issue by Gamerx007** [Ralim/IronOS#2016]
**Describe the bug**
 a weird issue with my TS101 display brightness when at 1 the screen appears to be off only at brightness level 2 then the screen lights up 

Brightness setting 2 - 5  work with no issues 

**To Reproduce**

 - Device: [e.g. TS101 ]
>  - Release: [v2.22.DED422AA4 ( 2024-12-07 ) & v2.22E.C308FE8C ( 05-11-23 )]
 - Power adapter being used: 5v PC USB 

Additional information 

 only at brightness level 2 then screen lights up.

( Brightness setting 2 - 5 work with no issues ) 

( is this a bug for the TS101 or have you already heard about it? )

**Comment by Ralim** [comment]
This is down to the specific OLED panel used. Better quality ones will work at lower drive levels.

**Comment by Gamerx007** [comment]
well that's sad

thanks for the info 

The animations in the menus are working very well on my TS101 


thanks again 😎👍
