### ISSUE TITLE
Convert hex format of firmware to atk for t80p alientek

### ISSUE THREAD

**Issue by utrumo** [Ralim/IronOS#2023]
I recently bought this soldering iron and found that there is no dfu mode in it.
It can only be flashed through upgrade mode using their proprietary windows firmware program. The problem is that it only supports atk firmware format.
Please tell me if it is possible to somehow convert the hex firmware to atk?

Here is a link to the firmware program:
https://en.alientek.com/download/p-10-10.html

**Comment by PRSXFENG** [comment]
This iron isn't supported?
Do not confuse Miniware TS80P and Alientek T80P
See
https://github.com/Ralim/IronOS/issues/1945
