### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by federck** [Ralim/IronOS#243]
**I'm submitting a ...**
  - [x] Feature request

 **Do you want to request a *feature* or report a *bug*?**

Insert GIFs instead of static images in the main menu (if possible)

**Steps to reproduce:**
1. Access main menu by pressing the nearest button to the micro-USB port

 **What are you running:**
  - Firmware Version: 2.03
  - PCB Version: 1

 **Other information** 

![37154978-eeaa3ef8-22e1-11e8-82bb-28123ecb8223](https://user-images.githubusercontent.com/33298498/37568722-75241dd8-2ad9-11e8-95f2-ed8a146b7541.gif)![37587768-7d93ee62-2b60-11e8-9a42-389b027b97f5](https://user-images.githubusercontent.com/33298498/44938044-ceb02380-ad7c-11e8-992e-fe3f61364135.gif)![37587766-7d64a170-2b60-11e8-9805-8b4be83921dd](https://user-images.githubusercontent.com/33298498/44938040-c657e880-ad7c-11e8-82b2-5398b65650d8.gif)![37154976-ee622bd6-22e1-11e8-99d9-0f1afbfd16c3](https://user-images.githubusercontent.com/33298498/37568725-75909986-2ad9-11e8-88f8-2b95a30801b6.gif)![37154979-eece8e84-22e1-11e8-8df9-6e1b2591ef95](https://user-images.githubusercontent.com/33298498/37568726-75b2c416-2ad9-11e8-896b-252cadd526d1.gif)![tuono](https://user-images.githubusercontent.com/33298498/44937780-4f6e2000-ad7b-11e8-8fc1-08c8819e608e.gif) (one time run)
![spuntaperenne](https://user-images.githubusercontent.com/33298498/37568727-7c4659aa-2ad9-11e8-817d-9ac54255380b.gif)![37587837-b3ec2b78-2b60-11e8-9f28-195c6a4a3e89](https://user-images.githubusercontent.com/33298498/44937953-36b23a00-ad7c-11e8-9a98-cef51f360003.gif)![37587838-b41ea72e-2b60-11e8-9286-e806c87a924b](https://user-images.githubusercontent.com/33298498/44937986-606b6100-ad7c-11e8-92e4-2730093b4697.gif)![calibperenne](https://user-images.githubusercontent.com/33298498/37568731-7caf0d56-2ad9-11e8-8f3c-90236bb9fdd1.gif)![saldperenne](https://user-images.githubusercontent.com/33298498/37568732-7cce940a-2ad9-11e8-8d42-64c56c260efb.gif)![tuono2](https://user-images.githubusercontent.com/33298498/44937796-63b21d00-ad7b-11e8-9c94-a2f213ee74e5.gif) (in perpetual running)
![37154978-eeaa3ef8-22e1-11e8-82bb-28123ecb8223](https://user-images.githubusercontent.com/33298498/37568846-fd18aabe-2ada-11e8-9ef7-27f95d845599.png)![37154977-ee865b0a-22e1-11e8-982d-c979cf0d0d06](https://user-images.githubusercontent.com/33298498/37568847-fd3d2d1c-2ada-11e8-971f-d10b24037173.png)![37155471-7e78c88c-22e3-11e8-8abc-3726245e6951](https://user-images.githubusercontent.com/33298498/37568848-fd5f086a-2ada-11e8-8d49-8299631ff303.png)![37154976-ee622bd6-22e1-11e8-99d9-0f1afbfd16c3](https://user-images.githubusercontent.com/33298498/37568849-fd86463c-2ada-11e8-88be-88feb4b91196.png)![37154979-eece8e84-22e1-11e8-8df9-6e1b2591ef95](https://user-images.githubusercontent.com/33298498/37568850-fdabcc90-2ada-11e8-8d57-7d60e5af2927.jpg)![tuono](https://user-images.githubusercontent.com/33298498/44937789-585ef180-ad7b-11e8-8ce9-e5b56b352ea0.jpg) (revisited better-looking PNGs)

**Comment by Mrkvozrout** [comment]
Great effort and interesting request. I just want to say that I personally like the static pictures better, but of course depends on majority or repo owner ;)

**Comment by JohnEdwa** [comment]
Animated GIFs as a filetype won't work, but if you combine the frames for each animation to [a sprite sheet](https://i.imgur.com/Q1OQM.png), the animation can be done by drawing a part of the image at a time.

Also, is that supposed to be a [Monkey Wrench](https://images-na.ssl-images-amazon.com/images/I/81uf87nZnrL._SX355_.jpg) or [Calipers](https://traceable.com/media/catalog/product/cache/2/image/9df78eab33525d08d6e5fb8d27136e95/3/4/3415mainweb_6.jpg)?  
Because I've always thought that icon is the wrench, but the animation (and well, calibration/calipers) makes me feel like I've been lied to my whole life.

**Comment by Ralim** [comment]
@JohnEdwa I think its meant to be Calipers :smile: 

I like this idea, there has also been calls for custom idle screens to be supported.
I think both of these things are doable, however I would like to first : 

1. Get 2.03 out with bug fixes
2. Look into #222 
3. Evaluate the left over flash space to pack in extra icons to allow for support for animated icons.

Also I feel most people will want the icons to *not* animate to make them easier to see and less confusing if your eyesight is poor. Not too sure on that one though.

**Comment by JohnEdwa** [comment]
> Also I feel most people will want the icons to not animate to make them easier to see and less confusing if your eyesight is poor. Not too sure on that one though.

Mmh, one thing that popped to my mind is that they should default to the full icon at the start. With the provided examples, the first few frames of the spanner and sleep animations are almost empty and very similar to each other.

**Comment by federck** [comment]
@JohnEdwa I confirm, it's a vernier type caliper, at least in my intent :smile: 

Designing icons was not too big of an effort; I'm open to modify styles as many times as needed. 
However, one-time-running icons would probably be a good compromise between static and animated.

**Comment by playday3008** [comment]
And so, I added intermediate frames, and it will even look like animation, only I don't know how to implement it.
https://github.com/playday3008/IronOS/tree/animated-icons
and maybe important info, `TS100_EN.hex` size 98 KB → 99 KB, I guess its probably nothing

P.S. yep, time to write the code that was asked for 3 years ago

**Comment by Ralim** [comment]
Hex file increasing is not as much of a concern; if we run out of flash space the CI will fail which will catch this. 
I believe TS80P is the device with the least flash at the moment.

**Comment by playday3008** [comment]
> Hex file increasing is not as much of a concern; if we run out of flash space the CI will fail which will catch this.
> I believe TS80P is the device with the least flash at the moment.

Then what's the problem?

**Comment by Ralim** [comment]
Check if the changes work for TS80P.
At the time this was shelved we had 0 spare flash space. Since then there was a lot of re-work of languages to increase the available flash space. My previous answer on this was from 2018 and as such is related to the state of things in 2018.

**Comment by playday3008** [comment]
Well
`TS80P_EN.hex` size 113 KB → 114 KB

**Comment by Ralim** [comment]
What is the object size that is printed out?
Hex size is extremely misleading
Or the binary file size?

If you run the build all script do all languages for all 4 irons build ?

**Comment by playday3008** [comment]
> If you run the build all script do all languages for all 4 irons build ?

Yep
![image](https://user-images.githubusercontent.com/18056374/110426925-37438e00-80a7-11eb-9a52-9ee31e7cdcba.png)

> Or the binary file size?

`TS80P_EN.bin` size 39.8 KB → 40.1 KB

**Comment by playday3008** [comment]
gcc `-Os` flag magic

**Comment by Ralim** [comment]
I see no reason not to do it then

**Comment by playday3008** [comment]
> I see no reason not to do it then

So, I have frames, you have brain, lets go mb
