### ISSUE TITLE
Boot Logo Options

### ISSUE THREAD

**Issue by Ralim** [Ralim/IronOS#292]
* **I'm submitting a ...**
 - [x] Feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature
* **What is the current behavior?**

Nil

* **What is the expected behavior?**

Add menu options for : 

* Turn on/off bootup logo
* Adjust display time [0-inf] 

I'm thinking this could be a single option for boot-up logo display.
With the options being [Off,1,5,10,30,Inf]

**Comment by JohnEdwa** [comment]
* **I'm submitting a ...**
  - [x] Feature request

Add menu option for :
* Show logo on: Boot/Wakeup/Both

**Comment by Eldenroot** [comment]
@Ralim - will you release v2.05 soon? I am asking because I have there 3 pcs of units from my friends to flash them to your fw from the stock one. Would be nice to use the latest version as possible. Thank you!
