### ISSUE TITLE
Feature: Custom GIF on boot-up

### ISSUE THREAD

**Issue by Jaqb2137** [Ralim/IronOS#446]
Feature request

Hi,
I have a simple ( I hope :D ) idea, that besides custom logo on boot-up, You can also implement a custom gif on iron startup. That could be a fun little feature.
Chears!

**Comment by Ralim** [comment]
You are welcome to create a pull request for this :) 
It would be rather limited though, total size of all frames would be 1kb, so about 5 frames

**Comment by Ralim** [comment]
if anyone would like to work on this,
It would require extending the python script to unpack the extra frames into the remainder of the flash page (aka just join them all end to end), and would need to store a framerate somewhere too.

First job is to decode the GIF into images
Then add these to the HEX.

**Comment by discip** [comment]
@Ralim
Is that https://github.com/Ralim/IronOS/pull/1180 sufficient? 😅

kind regards
