### ISSUE TITLE
Vietnam translation

### ISSUE THREAD

**Issue by uybv** [Ralim/IronOS#470]
Vietnam translation for the firmware.

[translation_vi.json.zip](https://github.com/Ralim/ts100/files/3187222/translation_vi.json.zip)

**Comment by Ralim** [comment]
Hey, sorry this slipped through the cracks.
If you could please open this as a pull request, would make this easier to test.

**Comment by discip** [comment]
@uybv
Since this was done by @alvinhochun this issue can be closed. 😊

thanks
