### ISSUE TITLE
TS100 - temperature limit - (Feature Request)

### ISSUE THREAD

**Issue by Evgen-24** [Ralim/IronOS#599]
* **I'm submitting a ...**
  - [ ] Bug report
  - [X] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Doesn't have this feature as far as i know.

* **What is the expected behavior?**

Limiting the maximum temperature of the soldering iron by setting a parameter in the menu

* **What is the motivation / use case for changing the behavior?**

To exclude accidental or erroneous overheating of the soldering iron tip. I ask you to add a new section (or subsection) of the menu, limiting the maximum temperature of the soldering iron. The maximum that can be set using the button in the main soldering iron mode. But this limitation should not apply to the turbo mode.
Example:
1. turbo mode is on and set to 390 degrees.
2. The maximum mode is set to 320 degrees.
During operation, using the buttons "A" and "B", the temperature of the soldering iron can only be adjusted to 320 degrees.
If during operation (regardless of temperature) you use the "turbo" mode (by holding the "A" button), then the soldering iron will warm up to 390 degrees.###

**Comment by discip** [comment]
@Evgen-24
What exactly is the point of this request?
You can set the limit by adjusting it from the soldering menu and the iron will not exceed this temperature unless you change it! 🤷‍♂️

Please consider closing this issue. 😊

thanks
