### ISSUE TITLE
Looking for ts100 fw version

### ISSUE THREAD

**Issue by filipszewczyk99** [Ralim/IronOS#628]
One time there was a version where there instead of power in watts was power in % and it was my favourite version can someone help me find it ?

**Comment by Ralim** [comment]
Is it your favorite because of just that feature?

**Comment by Scoredx** [comment]
No, it was very stable and I used it since I bought it

**Comment by Ralim** [comment]
I do not take down old versions, so they all still exist in the releases page. Most likely look for the one where we introduced the estimated power and then try the previous ones.

Mostly curious as to what has regressed for you in later firmwares.

**Comment by Scoredx** [comment]
In 2.0.6 afrer getting to designed temp I can hear beeping from under the oled

**Comment by Scoredx** [comment]
The temp reading was ok for me

**Comment by Ralim** [comment]
Interesting, your iron's caps must resonate nicely at the newer PWM frequency :|

**Comment by Scoredx** [comment]
Like 2 of my friends have problems with temp reading too

**Comment by Scoredx** [comment]
in the 2.0.6 and the newest one

**Comment by discip** [comment]
@filipszewczyk99
I think you will be surprised how much better the latest release is compared to the one you are referring to.
So try the latest release and close this issue please. 😊

thanks
