### ISSUE TITLE
No tip detected displays crazy temp.

### ISSUE THREAD

**Issue by GreekGeorge** [Ralim/IronOS#711]
Please edit this template and fill out all the information you can (where relevant). Failure to provide essential information can delay the response you receive.

_This is a [Bug/Feature Request/Question/Complaint]_

* **I have**
  - [X] Searched previous issues 
  - [ ] This is in _this_ firmware, not vendor "offical" firmware
  - [ ] This is not a bug in the vendor bootloader (aka DFU)
  - [ ] I have checked this is not already covered in the docs in `/Documentation`

* **What is the current behavior?**
When there is no tip, it shows a temp exceeding 450°C. Once the tip is reinserted it shows the proper temp.
* **What is the expected behavior?**
Should either display a message along the lines of "no tip detected" or simply not show a temperature.
***Steps to reproduce the bug:***
- Remove tip from iron
- Look at display (pic related)
* **What is the motivation / use case for changing the behavior?**
Doesn't really make sense.

* **What are you running:**
  - Firmware Version: 2.12
  - PCB Version: 2
  - Power Supply (Voltage and Current Rating) : 19V @ 3.42A Max.
![just the tip  is missing](https://user-images.githubusercontent.com/46611754/97710086-f4075c00-1ac3-11eb-97de-97545b1d30b4.jpeg)

**Comment by Ralim** [comment]
Ah yes,

There used to be a tip removed string that would be printed in this case, I can't remember if it was removed or if it has just been broken.

Shall have a look see for you soon.

**Comment by Firebie** [comment]
In a case of detailed view it shows 'Tip disconnected', in a case of classic view - temp.

**Comment by Ralim** [comment]
Hia,

I _believe_ this should now be fixed.
If you get some time, it would be fantastic if you check the latest CI build to test this (currently [this one](https://github.com/Ralim/ts100/actions/runs/452337083)).

Just scroll down and click on your model to download a zip of all of the languages.
🙏🏼 


I fixed this by in classic view just removing the iron for starting to solder.
While its not _ideal_ its a bit more intuitive and im open to other ideas

**Comment by GreekGeorge** [comment]
Cool! Thanks for working on the issue!
I'll check it out when I get home, and I'll let you know.

**Comment by GreekGeorge** [comment]
@Ralim be advised, the new flash doesn't display anything other than settings. Is this the function that you're after?
Pic related:
![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1609365025742_6750166164933599703.jpeg](https://user-images.githubusercontent.com/46611754/103383046-f3a63400-4af9-11eb-8282-fc26afa2417e.jpeg)

**Comment by Ralim** [comment]
Yep that's what I was thinking.

Open to other ideas of what to do, but felt that may be simplest ?

**Comment by GreekGeorge** [comment]
Oh, I thought it was a bug! lol
Maybe a simple message like "No Tip" or "NaN" or something I think would be nicer, and would fill the empty space in front of the settings symbol. Iron version maybe?

**Comment by Ralim** [comment]
Ask and you shall recieve 🤣 

Added an icon for no tip instead, is this nicer?
[here](https://github.com/Ralim/ts100/actions/runs/453592415)

**Comment by iLLiac4** [comment]
Tip disconnect detection does not work if the tip is removed during the soldering. It does work only when the iron is not heating up.

**Comment by Ralim** [comment]
Correct, that is normal as we don't want to kick user back to the main screen once you are in soldering mode.

**Comment by GreekGeorge** [comment]
Hey, that's pretty good!
Thank you for fixing the issue.
Greetings from Greece, and have a happy new year!
![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1609402465494_6750323198634764428.jpeg](https://user-images.githubusercontent.com/46611754/103401320-01d36f00-4b51-11eb-86fb-26c1b5757878.jpeg)
