### ISSUE TITLE
Where is the installation guide?

### ISSUE THREAD

**Issue by skorokithakis** [Ralim/IronOS#738]
The README references an installation guide but I can't find it anywhere. A link or some instructions on how to install the firmware would be great.

**Comment by Firebie** [comment]
https://github.com/Ralim/ts100/blob/master/Documentation/Upgrading.md

**Comment by skorokithakis** [comment]
Thanks, can this be added to the Readme (and hopefully be called "installation" rather than "upgrading")?

**Comment by Ralim** [comment]
This has been renamed to Flashing.md and a link added to the main readme
