### ISSUE TITLE
Flashing.md 404 Errors

### ISSUE THREAD

**Issue by flamespinner** [Ralim/IronOS#779]
The links under "main release" and "bleeding edge/latest" -- Releases page, and Actions page redirect to a github 404 error page. This is in https://github.com/Ralim/IronOS/blob/master/Documentation/Flashing.md

**Comment by pfeerick** [comment]
Closed by #780

**Comment by discip** [comment]
@flamespinner
Could you please check, if this works for you now, and if this should be the case, it would be nice, if you would close this issue.

**Comment by flamespinner** [comment]
My apologies. Yes, it works. I thought I had closed it, I will close it now.
