### ISSUE TITLE
[Request] Enable Wiki Edit

### ISSUE THREAD

**Issue by jLynx** [Ralim/IronOS#782]
Hi Ralim

Thanks for the awesome amount of work your have put into IronOS, its just amazing!

I am wanting to know if you can unlock the wiki as I would like to do some work on it if possible?

Thanks!

**Comment by Ralim** [comment]
Hi,
Wiki is locked as people kept putting promotional links in for everything :)
I've been trying to move all of the documentation into the repo so that its git tracked as well.
Always open to PR's for documentation at any time without issue.

**Comment by jLynx** [comment]
Ah I was more going to clean up the Wiki and formatting of everything as its a bit all over the place at the moment. Would you be able to make it editable for the next 30 minutes?

**Comment by Ralim** [comment]
Go for it

**Comment by jLynx** [comment]
You can lock it for now. I have done a bit of work on it. Still more that needs to be done which I can do later on :)

**Comment by Ralim** [comment]
❤️ 
Happy to add people who are doing good work to the list of people allowed

**Comment by jLynx** [comment]
Thanks very much. Will close this unless anyone else would like to help :)

**Comment by Ralim** [comment]
Dude, your doing the hard work here looking after a wiki; dont need to thank me 🥇
