### ISSUE TITLE
Custom boot logo appears mangled/distorted on TS80P

### ISSUE THREAD

**Issue by wlhlm** [Ralim/IronOS#796]
_This is a [Bug]_

* **I have**
  - [x] Searched previous issues 
  - [x] This is in _this_ firmware, not vendor "offical" firmware
  - [x] This is not a bug in the vendor bootloader (aka DFU)
  - [x] I have checked this is not already covered in the docs in `/Documentation`

* **What is the current behavior?**

Custom boot logo appears mangled using GH Actions [build](https://github.com/Ralim/IronOS/actions/runs/489962837) of (latest) commit https://github.com/Ralim/IronOS/commit/6d56ba3322959afdac235f8c955cfc69564f2a9c for TS80P.

* **What is the expected behavior?**

The logo should display correctly. Flashing back release version 2.13 (without reflashing the logo) shows the logo correctly on boot.

***Steps to reproduce the bug:***

1. generate logo from PNG using the included `img2ts100.py` script
2. upload logo as hex file
3. reboot soldering iron
4. *boot logo shows up distorted*
5. flash release build (version 2.13)
6. reboot soldering iron
7. *boot logo shows up correctly*

* **What are you running:**

  - Firmware Version: 6d56ba3322959afdac235f8c955cfc69564f2a9c (broken), 2.13 (working)
  - PCB Version: 31-12-20
  - Power Supply (Voltage and Current Rating): 5V normal USB power from host computer

[logo.zip](https://github.com/Ralim/IronOS/files/5824404/logo.zip) (includes source logo PNG and generated HEX files)

**Comment by Ralim** [comment]
Ah heck.

I'll jump on this tomorrow

**Comment by Ralim** [comment]
Should be fixed in new `master`.
my bad 😰

**Comment by wlhlm** [comment]
Can confirm working. Thanks for the quick fix!
