### ISSUE TITLE
Long-press + on idle to switch to temp. adj. should not immediately change temp.

### ISSUE THREAD

**Issue by alvinhochun** [Ralim/IronOS#825]
_This is a [~~Bug~~/Feature Request/~~Question~~/~~Complaint~~]_

* **I have**
  - Searched previous issues 
  - This is in _this_ firmware, not vendor "offical" firmware
  - This is not a bug in the vendor bootloader (aka DFU)
  - I have checked this is not already covered in the docs in `/Documentation`

* **What is the current behavior?**

When on the idle screen, long-pressing `+` will switch to temperature change mode, with the temperature already changed by +10.

Holding the button further will cause it to auto-repeat.

* **What is the expected behavior?**

When first entering temperature change mode, the temperature should not be changed by +10.

Holding the button further should not auto-repeat (i.e. cause further temperature changes) until the button was released and pressed again (but this is debatable).

***Steps to reproduce the bug:***

- Power on
- Hold + button until screen switches to temperature change mode
- Note that the displayed temperature is 10 degrees higher than the previously set value
- Continue holding the button and note that the set temperature keeps increasing

* **What is the motivation / use case for changing the behavior?**

The current behaviour is unintuitive.

* **What are you running:**

  - Firmware Version: custom build (cjk branch off f3488d7, so 2.14.1)
  - PCB Version: 3
  - Power Supply (Voltage and Current Rating) : not applicable

**Comment by Ralim** [comment]
Yep I get you.
Should be doable to do in the same way we handle this for existing a sub-menu.
