### ISSUE TITLE
Suggestion to remove .HEX files from Pinecil release

### ISSUE THREAD

**Issue by alvinhochun** [Ralim/IronOS#833]
_This is a Feature Request_

* **I have**
  - Searched previous issues 
  - This is in _this_ firmware, not vendor "offical" firmware
  - This is not a bug in the vendor bootloader (aka DFU)
  - I have checked this is not already covered in the docs in `/Documentation`

* **What is the current behavior?**

Pinecil releases contains both .BIN and .HEX files.

* **What is the expected behavior?**

.HEX files should not be needed because both `dfu-util` and the GD32 dfu tool knows .BIN files.

***Steps to reproduce the bug:***

(not applicable)

* **What is the motivation / use case for changing the behavior?**

Makes the release files less confusing and maybe shave off a few hundred KBs from the release?

* **What are you running:**

(not applicable)

**Comment by Ralim** [comment]
I mean I'm not against this, but I sort of left them on the basis of (a) I'm not paying for file storage and (b) they dont really hurt anyone, and if people are using the GD tool, using hex removes the _option_ of getting it wrong.

Could go either way, just felt normal to leave them all matching :)
