### ISSUE TITLE
Temperature stuck at 463 deg

### ISSUE THREAD

**Issue by balrog-kun** [Ralim/IronOS#842]
_This is a Question_

This is probably a hardware issue, I wonder if anyone has a pointer to which PCB element might need replacing.  I had the mosfet burn out and the tip glow red hot.  Replaced the mosfet and now everytime the TS100 starts heating up it quickly goes to 463°C and waits for the tip to cool down but that never happens.  I suspect the sensor sees a constant temperature and the only reason it shows lower values the first 500ms is due to the PID or low pass filter.

Tried two different tips.  Any ideas what may be wrong?

PCB version probably 1.

* **I have**
  - [x] Searched previous issues 
  - [x] This is in _this_ firmware, not vendor "offical" firmware
  - [x] This is not a bug in the vendor bootloader (aka DFU)
  - [ ] I have checked this is not already covered in the docs in `/Documentation`

**Comment by Ralim** [comment]
Most likely you have broken the op-amp in the readback path.

Can you dump all the values from the debugging menu and we can confirm all else is as it should be

**Comment by balrog-kun** [comment]
Good tip, very appreciated! I just upgraded from v1.08 to latest and this one directly says `NO TIP`, here's the debug menu dump:
```
17-01-21
HW G 197    (206 on USB power)
HW M 189  
HW P 96
Time (works)
Move (works)
RTip 10407  (~830 on USB)
CTip ~415   (30 on USB)
CHan ~289   (~301 on USB)
Vin (works)
PCB   1
PWR  0
Max  413
```

**Comment by Ralim** [comment]
Hi,

Yeah that looks to me like something in the readback path is broken.
Suspects are this block:
![image](https://user-images.githubusercontent.com/5425387/106966522-a3299280-6799-11eb-918f-71fc734a0372.png)

**Comment by balrog-kun** [comment]
Awesome, I have the list of things to test now.  Closing the issue to avoid inflating the issue list but I'll post an update if I find which element(s) was the culprit, for google's reference.
