### ISSUE TITLE
Broken wiki links

### ISSUE THREAD

**Issue by adatum** [Ralim/IronOS#859]
Clicking on the "Installation/Flashing" or "Mods" links in the wiki sidebar redirects to the "Home" wiki page, with a GitHub banner message saying "You do not have permission to update this wiki."

At least the installation/flashing information is available at https://github.com/Ralim/IronOS/blob/master/Documentation/Flashing.md

**Comment by Ralim** [comment]
Removed the dead links.

Wiki is locked to prevent people adding in commision links to parts again. _sigh_

**Comment by adatum** [comment]
Is there a reason why the wiki does not include the documentation? I thought the link was meant to point to the documentation.

**Comment by Ralim** [comment]
Documentation is stored in the repo rather than the wiki so that it is kept up to date with the firmware.
