### ISSUE TITLE
URUAV XT-60 to USB module

### ISSUE THREAD

**Issue by Shpek** [Ralim/IronOS#868]
Hello,

This is just a suggestion to add a link to this module to the [TS80 power sources](https://github.com/Ralim/IronOS/wiki/TS80-Power-Sources) wiki page: [URUAV XT-60 to USB module](https://www.banggood.com/URUAV-XT-60-to-USB-Charger-Converter-Support-3S-6S-LiPo-Battery-10_5V-32V-Input-3V-20V-Output-45W-Max-Fast-Charging-Adapter-For-RC-Racing-Drone-p-1475876.html). It's really convenient for drone enthusiasts since you can use your battery packs directly. TS80 with IronOS works great with it on 9V and 12V (tested it with 3S and 4S battery packs) and can work for hours without breaking a sweat.

Thanks for the awesome software.

**Comment by Ralim** [comment]
Have added it to the wiki page :) thank you ❤️
