### ISSUE TITLE
`build.sh` missing

### ISSUE THREAD

**Issue by devydd** [Ralim/IronOS#893]
The file `build.sh` was removed in commit f831b74e57fc99fc905eebdcb273d1d1a8f98872. Was that intentional?

Of course I can manually run:
```bash
docker-compose run --rm builder /bin/bash /build/ci/buildAll.sh
```
but that script was very convenient.

**Comment by Ralim** [comment]
I removed it as all of the ci work stopped using it, but happy to bring it back

**Comment by devydd** [comment]
It was that little file that allowed me to jump right into the code and test the modifications without spending any time thinking about the build process. IMHO: it's a keeper :)
