### ISSUE TITLE
Update Pinecil flashing guide for Windows

### ISSUE THREAD

**Issue by adokitkat** [Ralim/IronOS#967]
_This is a Complaint_

Hello, I have bought Pinecil and was trying to update from a factory firmware to the latest IronOS 2.15. 
However, the GD32 DFU update tool recommended in _Flashing.md_ guide did not recognise my device on Windows 10 machine.
Later I searched Pine64 Pinecil wiki page and found their update tool - _Pinecil Firmware Updater_ - which recognised the Pinecil and just worked.

While updating the firmware, it said I don't have WinUSB drivers installed and installed it for me. I suspect it might be the reason for GD32 DFU update tool not recognising my Pinecil in the first place.

I think it should be mentioned in _Flashing.md_ guide.

**Comment by adokitkat** [comment]
> Added note to the file for future 😄

Unfortunately it didn't change anything for me :/ I installed the drivers but GD32 DFU updater still doesn't recognise the Pinecil.
The original Pinecil Firmware updater still works thought.
In Device Manager the Pinecil is listed under Universal Serial Bus devices as Unknown device.

**Comment by alvinhochun** [comment]
GD32's DFU tool needs their own GD32 DFU driver, *not* WinUSB.
