### ISSUE TITLE
more realistic animation of the wrench

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS#969]
As recommended by @Ralim & @alvinhochun I am proposing hereby a request for changing the animation of the wrench in the main menu (**`Advanced settings`**) from ***sliding in*** diagonally, to ***rotating*** around one end *(preferably around the top left end)*.

> > While you are at it, would you mind to change the animation style oft the _**wrench**_, used for the **`Advanced options`** menu, as well?
> > I thought about the movement of the real thing _(rotating around one end)_, not sliding in. 😁
>
> IMO better handle that in another issue.

_Originally posted by @alvinhochun in https://github.com/Ralim/IronOS/issues/892#issuecomment-831778208_

> > I thought about the movement of the real thing (rotating around one end), not sliding in. 😁
> 
> I would create a seperate issue to track that one

_Originally posted by @Ralim in https://github.com/Ralim/IronOS/issues/892#issuecomment-831784671_

thanks in advance

**Comment by federicodilo** [comment]
It is not easy to draw a better wrench in a 16 × 16 square, or at least one that is recognizable.
Furthermore, as it is drawn diagonally, it must be made smaller and therefore less "legible".

**Comment by discip** [comment]
The idea is not to depict the whole wrench at any point of the animation, rather than seeing it rotate, even if parts of it get cut away in the process.
I tried to create a sample of how it could look like. 😅
![wrench](https://user-images.githubusercontent.com/53649486/118326186-ec118580-b504-11eb-987c-5a20a9b0fc34.gif)
<details>
  <summary>
    <b>individual frames</b>
  </summary>

1. ![wrench_page_0001](https://user-images.githubusercontent.com/53649486/118326808-c5a01a00-b505-11eb-822f-7e01812ff46c.png)
2. ![wrench_page_0002](https://user-images.githubusercontent.com/53649486/118326809-c638b080-b505-11eb-96a8-1ef354cf493e.png)
3. same as the 1st
4. ![wrench_page_0004](https://user-images.githubusercontent.com/53649486/118326811-c6d14700-b505-11eb-8c7a-d6a55a011399.png)

</details>

regards

**Comment by HanaO00** [comment]
Hello, why not put a spinning gear? Also, it will be a little more familiar for some people compared to the settings of the phones.
Something like this
![spinning](https://user-images.githubusercontent.com/17810985/118332637-b2437d80-b50a-11eb-9d20-501528725696.gif)

**Comment by discip** [comment]
@HanaO00
1. The wrench was originally there, it just should look the right way. 😊
2. As @federicodilo stated, there is only a
> 16 × 16 square

and only ***3 frames*** where this delicate animation (2 meshing gears) has to fit into.
The .gif provided above, is actually fulfilling these requirements, but I doubt these gears will. 🤷‍♂️

**Comment by HanaO00** [comment]
Ah, I didn't know that there were only 3 frames, I'm only offering a few ideas, that may give you some too, I found this, It is also possible to play with a zoom / dezoom maybe (smaller to bigger)
![wrench](https://user-images.githubusercontent.com/17810985/118336231-8aa3e380-b511-11eb-91f9-f170f7270b06.jpg)

**Comment by federicodilo** [comment]
Here I have two new proposals:
![tuono](https://user-images.githubusercontent.com/68966053/118356622-70e8b780-b576-11eb-8282-932179b21947.gif) ![gear1](https://user-images.githubusercontent.com/68966053/118356451-90331500-b575-11eb-87e3-4e4b7713a8a0.gif)

The current animation of the two thunders always give me the impression to be "glitchy".
Whatever, let's try to find a compromise.

**Comment by HanaO00** [comment]
The lightning could be confused with the one present in the power settings, maybe?
Difficult to see how it looks on the soldering iron screen, better than here I imagine, the variant is very interesting, an additional idea, there is this type of key too, which can have an opening movement and closing
![Uploading englandkey.png…]()

**Comment by federicodilo** [comment]
Yes, sorry, the lightning it's intended to possibly replace the animation in power settings.

**Comment by HanaO00** [comment]
Oh yes sorry I read it wrong, I like the new proposal of the lightning

**Comment by HanaO00** [comment]
Oh yes sorry I read it wrong, I like the new proposal of the lightning
I confirm for the second variant
For the last one wrench, maybe reverse the animation (opening, there is closing)

**Comment by federicodilo** [comment]
Each gif is designed so that the last frame retains a certain harmony so as to be "readable" if the animations are deactivated.
As for the wrench I think it is better to have it less open in the last frame.

**Comment by HanaO00** [comment]
Interesting, thank you for all this info

**Comment by Vinigas** [comment]
![ironos_wrench](https://user-images.githubusercontent.com/6695244/118377083-6b21bf00-b5d4-11eb-9f96-1b7eb5b2113c.gif)
What about this ?

**Comment by HanaO00** [comment]
I prefer the one made by federicodilo which does not go beyond the frame personally

**Comment by Vinigas** [comment]
![ironos_wrench](https://user-images.githubusercontent.com/6695244/118391781-c5f00080-b63e-11eb-80c6-1aa00dc0e04f.gif)
v2. Opinions ?

**Comment by HanaO00** [comment]
As federicodilo said there are 3 frames in the gif, I like the very last one

**Comment by discip** [comment]
Good morning everyone,
as @federicodilo mentioned above:

> Each gif is designed so that the last frame retains a certain harmony so as to be "readable" if the animations are deactivated.

and even before that, these annotations were addressing the same issue:

> 1. ![wrench_page_0001](https://user-images.githubusercontent.com/53649486/118334454-ecfae500-b50d-11eb-9b9b-b9d1692bd2ca.png) _has to be the **first**_
> 2. ![wrench_page_0002](https://user-images.githubusercontent.com/53649486/118334455-ed937b80-b50d-11eb-823b-e40d4fe27844.png)
> 3. ![wrench_page_0003](https://user-images.githubusercontent.com/53649486/118334451-ec624e80-b50d-11eb-8117-f1f5c6dcaa81.png) _hast to be the **last**_

the last frame has to be the most *representable*.

And as the original design is the one, which should be kept, since the initial idea was not to replace the icon, but rather to make it look natural, remember? 😁
My suggestion is to go with the original wrench, but slightly shortened to fit the whole tool in every frame, make it go clockwise and place the most "readable" frame at the end, for cases where animation or looping is turned off:

![wrench](https://user-images.githubusercontent.com/53649486/118570234-086b2780-b77c-11eb-91bf-50114ac10f97.gif)

<details>
  <summary>
    <b>don't click</b>
  </summary>

just in case
1. ![1](https://user-images.githubusercontent.com/53649486/118571203-c347f500-b77d-11eb-8dfb-680373395ee0.png)
2. ![2](https://user-images.githubusercontent.com/53649486/118571204-c3e08b80-b77d-11eb-852b-9e645679c549.png)
3. ![3](https://user-images.githubusercontent.com/53649486/118571205-c3e08b80-b77d-11eb-815f-51d0dbfd2aa0.png)

</details>

kind regards

**Comment by discip** [comment]
@Ralim
@alvinhochun
If this is not to hard and you agree with this change, it would be nice if someone could implement this.

thanks
kind regards
