### ISSUE TITLE
TS80 not working with type-c charger

### ISSUE THREAD

**Issue by Fxlr8** [Ralim/IronOS#976]
When I power my TS80 iron from a regular USB charger it works fine, but every time I try to power it from type-c charger it does not work at all. I have tried three of them: 100w Macbook pro, and two other type-c chargers with power delivery capable of 5V, 9V, 12V. I have upgraded to the latest 2.15 firmware but it didn't help.

**Comment by Fxlr8** [comment]
Ah, I see. This is sad https://github.com/Ralim/IronOS/issues/349#issuecomment-417179746

**Comment by Ralim** [comment]
Correct, TS80 can only use QC sources, not PD.
PD sources require the TS80P
