### ISSUE TITLE
sequre sq-001

### ISSUE THREAD

**Issue by bm16ton** [Ralim/IronOS#984]
Hello, this project is amazing! I have a Sequre SQ-001 which appears to be a TS1000 clone. I found this project in a review for my iron here https://oscarliang.com/sequre-q-001/ He claims to be using this firmware on the SQ-001  without problems. Just curious if you have heard of the SQ-001 and if plans to officially support/list it. Also if i take the chance and flash iron IronOS what possible issues should i be aware of, and/or any kinda tests I should do? Thanks you! Again awesome and super impressive work!

UPDATE; Flashed the TS100 firmware , went thru every setting, did every calibration (no way to test that except for input voltage which is accurate), and everything seems great!

**Comment by Ralim** [comment]
Hi,

Everything _should_ work totally fine as they are a clone. Just don't list them officially as the manufacturer tends to have poor support if they fail for one reason or another and trying not to encourage the clone market :)

That said, it's a hardware copy so everything should work and act like the Ts100.

Have fun, and may it work well for you

**Comment by bm16ton** [comment]
Well for the most part it works! But it does lock up a fair amount. I have been running it with the extra info on home screen but will try it wo that setting. Have tried multiple psu's so dont  think they are the issue. Will test more as I can.

**Comment by maoneid** [comment]
After I use Windows 10 , it was successfully updated to [V2.23](https://github.com/Ralim/IronOS/releases/tag/v2.23). 
I don't know why that Windows 11 has problem to copy .hex file to the STM32. 

Is there any technical information about this error?
