### ISSUE TITLE
Ts80p temperature problem.

### ISSUE THREAD

**Issue by LousyFox** [Ralim/IronOS#996]
Hello.  I am having some problems with the temperature reading on the displays.  If I use a TS-B02 tip and set the temperature to 330 degrees, then on the displays it jumps sharply from 330 to 340, and the readings change abruptly, not static.
 On the TS-K4 sting, if I set the temperature to 330, then the readings change from 320 to 370 there back, not static.

**Comment by Ralim** [comment]
Hello, please add back in the missing information block that you have not answered about your model and power supply :)

**Comment by 12321312** [comment]
TS80P ironos 
30W original

**Comment by Ralim** [comment]
What model number, what voltage, what firmware version.
firmware version should be 2.15.XXXXXYYYY when you read it off the device.

Are your tips the official ones from Miniware (have logo laser engraved on them) ?

**Comment by 12321312** [comment]
![20210609_135022](https://user-images.githubusercontent.com/22121733/121307676-709bcc00-c92a-11eb-9ed6-5b38e8ef580c.jpg)
![20210609_134946](https://user-images.githubusercontent.com/22121733/121307683-72658f80-c92a-11eb-94b3-41c28968db5c.jpg)
![16232217763138386016422942434266](https://user-images.githubusercontent.com/22121733/121307740-81e4d880-c92a-11eb-8334-f2c42a3d7071.jpg)
![16232218194581748423197538992704](https://user-images.githubusercontent.com/22121733/121307799-94f7a880-c92a-11eb-8e1c-b20069f71430.jpg)

**Comment by 12321312** [comment]
Was stitched to the official firmware, there is no such problem.  The problem is on this firmware.

**Comment by 12321312** [comment]
https://youtube.com/shorts/-9s33oEp7Lw?feature=share
 More clearly

**Comment by Ralim** [comment]
Hi,
Thank you for providing the firmware version for confirmation. ❤️ 

Looking at the video it looks like you are seeing the normal movement of the last digit that is normal as that is the firmware showing "live" the exact reading. (Rather than hiding this like official firmware).

There is already a ticket about adding a filter to hide this but this has not yet been implemented.

Also you can try using it with the power pulses turned off as these can make this situation worse as the firmware inserts small pulses of power to keep power banks awake, but this comes at the detriment of the temperature regulation.

**Comment by 12321312** [comment]
Thanks for explaining.  I thought it was a marriage and was very sad.  How do I turn off impulses?  Can I have a mini-guide?

**Comment by 12321312** [comment]
Thanks for explaining.  I thought it was a marriage and was very sad.  How do I turn off impulses?  Can I have a mini-guide?

**Comment by Ralim** [comment]
I will also add the movement of the numbers are of no detriment to performance. (just ugly)

I believe if you go into the menu -> Advanced settings -> Power pulse you should be able to set it to be turned off. (Menu names depending on translation)

**Comment by 12321312** [comment]
Thank you very much.  I will be looking forward to an update where this feature will be.  :)
